USE ROLE ACCOUNTADMIN;
CREATE DATABASE IF NOT EXISTS MS_RAW;
USE DATABASE MS_RAW;


with schema_cte as (
    SELECT DISTINCT
        REPLACE(REPLACE(SCHEMA_NAME,'REEDONLINE_',''),'RESTRICTED','DBO') AS MS_SCHEMA_NAME,
    FROM ROL_RAW.INFORMATION_SCHEMA.SCHEMATA 
    WHERE SCHEMA_NAME IN ('REEDONLINE_DBO'
                         ,'REEDONLINE_DUPLICATEJOBSERVICE'
                         ,'REEDONLINE_JOBIMPORT'
                         ,'REEDONLINE_JOBS'
                         ,'REEDONLINE_RECRUITERJOBSTEXTKERNEL'
                         ,'REEDONLINE_RESTRICTED')
)
SELECT
    LISTAGG('CREATE SCHEMA IF NOT EXISTS MS_RAW.' || MS_SCHEMA_NAME || ';\n')
        WITHIN GROUP (ORDER BY MS_SCHEMA_NAME)
        as "--stmnt"
    FROM schema_cte
;

CREATE SCHEMA IF NOT EXISTS MS_RAW.DBO;
CREATE SCHEMA IF NOT EXISTS MS_RAW.DUPLICATEJOBSERVICE;
CREATE SCHEMA IF NOT EXISTS MS_RAW.JOBIMPORT;
CREATE SCHEMA IF NOT EXISTS MS_RAW.JOBS;
CREATE SCHEMA IF NOT EXISTS MS_RAW.RECRUITERJOBSTEXTKERNEL;

