-- Copies the MSSQL metadata from ROL_RAW.REEDONLINE_META to MS_RAW.META
USE ROLE ACCOUNTADMIN;
CREATE SCHEMA IF NOT EXISTS MS_RAW.META;

-- COLUMNS
CREATE OR REPLACE TABLE MS_RAW.META.COLUMNS AS
SELECT * REPLACE('MSDB' AS TABLE_CATALOG) 
FROM ROL_RAW.REEDONLINE_META.COLUMNS
;

-- KEY_COLUMN_USAGE
CREATE OR REPLACE TABLE MS_RAW.META.KEY_COLUMN_USAGE AS
SELECT * REPLACE('MSDB' AS TABLE_CATALOG, 'MSDB' AS CONSTRAINT_CATALOG) 
FROM ROL_RAW.REEDONLINE_META.KEY_COLUMN_USAGE
;

-- REFERENTIAL_CONSTRAINTS
CREATE OR REPLACE TABLE MS_RAW.META.REFERENTIAL_CONSTRAINTS AS
SELECT * REPLACE('MSDB' AS CONSTRAINT_CATALOG, 'MSDB' AS UNIQUE_CONSTRAINT_CATALOG) 
FROM ROL_RAW.REEDONLINE_META.REFERENTIAL_CONSTRAINTS
;

-- TABLES
CREATE OR REPLACE TABLE MS_RAW.META.TABLES AS
SELECT * REPLACE('MSDB' AS TABLE_CATALOG) 
FROM ROL_RAW.REEDONLINE_META.TABLES
;

-- TABLE_CONSTRAINTS
CREATE OR REPLACE TABLE MS_RAW.META.TABLE_CONSTRAINTS AS
SELECT * REPLACE('MSDB' AS TABLE_CATALOG, 'MSDB' AS CONSTRAINT_CATALOG) 
FROM ROL_RAW.REEDONLINE_META.TABLE_CONSTRAINTS
;
