USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE TABLE MS_RAW.DBT_META.NEW_DATETIME_COLUMNS
AS
SELECT SF_TABLE_CATALOG, 
       SF_TABLE_SCHEMA, 
       SF_TABLE_NAME, 
       SF_COLUMN_NAME, 
       SF_DATA_TYPE,
       MS_DATA_TYPE::VARCHAR AS MS_DATA_TYPE,
       'BIRTH'::VARCHAR AS NEW_COLUMN_NAME,
       'DATE'::VARCHAR AS NEW_DATA_TYPE,
       COLUMN_KEY
FROM MS_RAW.DBT_META.SF_COLUMNS 
WHERE sf_column_name = 'DATE_OF_BIRTH'
;


-- delete the date part from the column name
INSERT INTO MS_RAW.DBT_META.NEW_DATETIME_COLUMNS
SELECT SF_TABLE_CATALOG, 
       SF_TABLE_SCHEMA, 
       SF_TABLE_NAME, 
       SF_COLUMN_NAME, 
       SF_DATA_TYPE,
       MS_DATA_TYPE,
       REPLACE(REPLACE(SF_COLUMN_NAME,'DATE_',''),'_DATE','') AS NEW_COLUMN_NAME,
       CASE WHEN sf_data_type = 'DATE' THEN 'DATE' END AS NEW_DATA_TYPE,
       COLUMN_KEY
FROM MS_RAW.DBT_META.SF_COLUMNS 
WHERE 1 = 1
  AND COLUMN_KEY NOT IN (SELECT COLUMN_KEY FROM  MS_RAW.DBT_META.NEW_DATETIME_COLUMNS)
  AND sf_column_name like ANY ('DATE\\_%','%\\_DATE\\_%','%\\_DATE') ESCAPE '\\'
  AND sf_data_type IN ('DATE','TIMESTAMP_TZ')
ORDER BY ALL
;
SELECT NEW_COLUMN_NAME FROM MS_RAW.DBT_META.NEW_DATETIME_COLUMNS 
 WHERE NEW_COLUMN_NAME LIKE '%DATE%' GROUP BY ALL ORDER BY ALL
;

INSERT INTO MS_RAW.DBT_META.NEW_DATETIME_COLUMNS
SELECT SF_TABLE_CATALOG, 
       SF_TABLE_SCHEMA, 
       SF_TABLE_NAME, 
       SF_COLUMN_NAME, 
       SF_DATA_TYPE,
       MS_DATA_TYPE,
       SF_COLUMN_NAME as NEW_COLUMN_NAME,
       NULL AS NEW_DATA_TYPE,
       COLUMN_KEY
FROM MS_RAW.DBT_META.SF_COLUMNS 
WHERE COLUMN_KEY NOT IN (SELECT COLUMN_KEY FROM  MS_RAW.DBT_META.NEW_DATETIME_COLUMNS)
  AND  sf_data_type IN ('DATE','TIMESTAMP_TZ')
ORDER BY ALL;

select * from MS_RAW.DBT_META.NEW_DATETIME_COLUMNS
order by all;

