SELECT *
  FROM MS_RAW.DBT_META.NEW_DATETIME_COLUMNS 
--  WHERE NEW_column_name like ANY ('DATE\\_%','%\\_DATE\\_%','%\\_DATE') ESCAPE '\\'
ORDER BY ALL;

-- _ON -> _AT for TIMESTAMP_NTZ
/*
SELECT SF_COLUMN_NAME, LEFT(NEW_COLUMN_NAME, LENGTH(NEW_COLUMN_NAME) - 3) || '_AT'
FROM MS_RAW.DBT_META.NEW_DATETIME_COLUMNS
WHERE ENDSWITH(SF_COLUMN_NAME,'_ON') AND NEW_DATA_TYPE = 'TIMESTAMP_NTZ'
GROUP BY ALL
ORDER BY ALL
;
*/
UPDATE MS_RAW.DBT_META.NEW_DATETIME_COLUMNS
   SET NEW_COLUMN_NAME = LEFT(NEW_COLUMN_NAME, LENGTH(NEW_COLUMN_NAME) - 3) || '_AT'
WHERE ENDSWITH(NEW_COLUMN_NAME,'_ON') AND NEW_DATA_TYPE = 'TIMESTAMP_NTZ'
;
/*
SELECT SF_COLUMN_NAME, NEW_COLUMN_NAME
FROM MS_RAW.DBT_META.NEW_DATETIME_COLUMNS
WHERE ENDSWITH(SF_COLUMN_NAME,'_ON') AND NEW_DATA_TYPE = 'TIMESTAMP_NTZ'
GROUP BY ALL
ORDER BY ALL
;
*/

--  NOT ENDSWITH(NEW_COLUMN_NAME,'_AT') -> _AT for TIMESTAMP_NTZ
/*
SELECT SF_COLUMN_NAME, NEW_COLUMN_NAME --, LEFT(SF_COLUMN_NAME, LENGTH(SF_COLUMN_NAME) - 3) || '_AT'
FROM MS_RAW.DBT_META.NEW_DATETIME_COLUMNS
WHERE NOT ENDSWITH(NEW_COLUMN_NAME,'_ON') 
  AND NOT ENDSWITH(NEW_COLUMN_NAME,'_AT') 
  AND NEW_DATA_TYPE = 'TIMESTAMP_NTZ'
GROUP BY ALL
ORDER BY ALL
;
*/
UPDATE MS_RAW.DBT_META.NEW_DATETIME_COLUMNS
   SET NEW_COLUMN_NAME = NEW_COLUMN_NAME || '_AT'
WHERE NOT ENDSWITH(NEW_COLUMN_NAME,'_AT')
  AND NEW_DATA_TYPE = 'TIMESTAMP_NTZ'
;
/*
SELECT SF_COLUMN_NAME, NEW_COLUMN_NAME
FROM MS_RAW.DBT_META.NEW_DATETIME_COLUMNS
WHERE ENDSWITH(NEW_COLUMN_NAME,'_AT') 
  AND NEW_DATA_TYPE = 'TIMESTAMP_NTZ'
GROUP BY ALL
ORDER BY ALL
;
*/

/*
SELECT SF_COLUMN_NAME, NEW_COLUMN_NAME || '_DATE' 
FROM MS_RAW.DBT_META.NEW_DATETIME_COLUMNS
WHERE 1 = 1
--  AND NOT ENDSWITH(NEW_COLUMN_NAME,'_AT') 
  AND NEW_DATA_TYPE = 'DATE'
  AND NOT NEW_COLUMN_NAME ILIKE ANY (--'%\\_ON','%\\_FROM','%\\_TO','%\\_UNTIL',
                                     'FROM','TO','OF_BIRTH','APPLICATION_END_RANGE'
                                    ) ESCAPE '\\'
GROUP BY ALL
ORDER BY ALL
;
*/

UPDATE MS_RAW.DBT_META.NEW_DATETIME_COLUMNS
   SET NEW_COLUMN_NAME = NEW_COLUMN_NAME || '_DATE'
WHERE NEW_DATA_TYPE = 'DATE'
  AND NOT NEW_COLUMN_NAME ILIKE ANY (--'%\\_ON','%\\_FROM','%\\_TO','%\\_UNTIL',
                                     'FROM','TO','OF_BIRTH','APPLICATION_END_RANGE'
                                    ) ESCAPE '\\'
;

/*
SELECT SF_COLUMN_NAME, NEW_COLUMN_NAME
FROM MS_RAW.DBT_META.NEW_DATETIME_COLUMNS
WHERE 1=1
  AND ENDSWITH(NEW_COLUMN_NAME,'_DATE') 
  AND NEW_DATA_TYPE = 'DATE'
GROUP BY ALL
ORDER BY ALL
;
*/

/*
SELECT SF_COLUMN_NAME, NEW_COLUMN_NAME
FROM MS_RAW.DBT_META.NEW_DATETIME_COLUMNS
WHERE 1=1
  AND NOT ENDSWITH(NEW_COLUMN_NAME,'_DATE') 
  AND NEW_DATA_TYPE = 'DATE'
GROUP BY ALL
ORDER BY ALL
;
*/

/*
SELECT SF_COLUMN_NAME, 
       CASE WHEN NEW_COLUMN_NAME IN ('FROM','TO') 
                 THEN 'HISTORY_' || NEW_COLUMN_NAME || '_DATE'
            WHEN NEW_COLUMN_NAME = 'APPLICATION_END_RANGE'
                 THEN 'APPLICATION_END_DATE'
            WHEN NEW_COLUMN_NAME = 'OF_BIRTH'
                 THEN 'BIRTH_DATE'
            ELSE NEW_COLUMN_NAME
       END AS NEW_COLUMN_NAME
FROM MS_RAW.DBT_META.NEW_DATETIME_COLUMNS
WHERE 1 = 1
  AND NEW_COLUMN_NAME IN ('FROM','TO','APPLICATION_END_RANGE','OF_BIRTH')
ORDER BY ALL
;
*/

UPDATE MS_RAW.DBT_META.NEW_DATETIME_COLUMNS
   SET NEW_COLUMN_NAME = 
       CASE WHEN NEW_COLUMN_NAME IN ('FROM','TO') 
                 THEN 'HISTORY_' || NEW_COLUMN_NAME || '_DATE'
            WHEN NEW_COLUMN_NAME = 'APPLICATION_END_RANGE'
                 THEN 'APPLICATION_END_DATE'
            WHEN NEW_COLUMN_NAME = 'OF_BIRTH'
                 THEN 'BIRTH_DATE'
            ELSE NEW_COLUMN_NAME
       END
WHERE NEW_COLUMN_NAME IN ('FROM','TO','APPLICATION_END_RANGE','OF_BIRTH')
;
/*
SELECT SF_COLUMN_NAME, NEW_COLUMN_NAME
FROM MS_RAW.DBT_META.NEW_DATETIME_COLUMNS
WHERE NEW_COLUMN_NAME IN ('HISTORY_FROM_DATE','HISTORY_TO_DATE','APPLICATION_END_DATE','BIRTH_DATE')
GROUP BY ALL
ORDER BY ALL
;
*/

/*
SELECT SF_COLUMN_NAME, NEW_COLUMN_NAME
FROM MS_RAW.DBT_META.NEW_DATETIME_COLUMNS
WHERE 1=1
  AND NOT ENDSWITH(NEW_COLUMN_NAME,'_DATE') 
  AND SF_DATA_TYPE = 'DATE'
  AND NEW_DATA_TYPE != 'DATE'
GROUP BY ALL
ORDER BY ALL
;
*/

UPDATE MS_RAW.DBT_META.NEW_DATETIME_COLUMNS
   SET NEW_DATA_TYPE = 'DATE'
WHERE SF_DATA_TYPE = 'DATE'
;

/*
SELECT SF_COLUMN_NAME, NEW_COLUMN_NAME
FROM MS_RAW.DBT_META.NEW_DATETIME_COLUMNS
WHERE 1=1
  AND NOT ENDSWITH(NEW_COLUMN_NAME,'_DATE') 
  AND NEW_DATA_TYPE = 'DATE'
GROUP BY ALL
ORDER BY ALL
;
*/