SELECT SF_DATA_TYPE, NEW_DATA_TYPE, COUNT(*)
FROM MS_RAW.DBT_META.NEW_DATETIME_COLUMNS
GROUP BY ALL
ORDER BY ALL
;

SELECT * REPLACE (LEFT(NEW_COLUMN_NAME,LENGTH(NEW_COLUMN_NAME)-3) AS NEW_COLUMN_NAME
                  , 'DATE' AS NEW_DATA_TYPE 
                 )
FROM MS_RAW.DBT_META.NEW_DATETIME_COLUMNS
WHERE SF_DATA_TYPE = 'TIMESTAMP_TZ'
  AND NEW_DATA_TYPE = 'TIMESTAMP_NTZ'
  AND SF_COLUMN_NAME ILIKE ANY ('%\\FROM','%\\TO','%\\UNTIL') ESCAPE '\\'
  AND NEW_COLUMN_NAME ILIKE ANY ('%\\FROM\\_AT','%\\TO\\_AT','%\\UNTIL\\_AT') ESCAPE '\\'
ORDER BY ALL
;
INSERT INTO MS_RAW.DBT_META.NEW_DATETIME_COLUMNS
SELECT * REPLACE (LEFT(NEW_COLUMN_NAME,LENGTH(NEW_COLUMN_NAME)-3) AS NEW_COLUMN_NAME
                  , 'DATE' AS NEW_DATA_TYPE 
                 )
FROM MS_RAW.DBT_META.NEW_DATETIME_COLUMNS
WHERE SF_DATA_TYPE = 'TIMESTAMP_TZ'
  AND NEW_DATA_TYPE = 'TIMESTAMP_NTZ'
  AND SF_COLUMN_NAME ILIKE ANY ('%\\FROM','%\\TO','%\\UNTIL') ESCAPE '\\'
  AND NEW_COLUMN_NAME ILIKE ANY ('%\\FROM\\_AT','%\\TO\\_AT','%\\UNTIL\\_AT') ESCAPE '\\'
;
INSERT INTO MS_RAW.DBT_META.NEW_DATETIME_COLUMNS
SELECT * REPLACE (LEFT(NEW_COLUMN_NAME,LENGTH(NEW_COLUMN_NAME)-3) || '_ON' AS NEW_COLUMN_NAME
                  , 'DATE' AS NEW_DATA_TYPE 
                 )
FROM MS_RAW.DBT_META.NEW_DATETIME_COLUMNS
WHERE SF_DATA_TYPE = 'TIMESTAMP_TZ'
  AND NEW_DATA_TYPE = 'TIMESTAMP_NTZ'
  AND NEW_COLUMN_NAME ILIKE '%\\_AT' ESCAPE '\\'
  AND NOT NEW_COLUMN_NAME ILIKE ANY ('%\\FROM\\_AT','%\\TO\\_AT','%\\UNTIL\\_AT') ESCAPE '\\'
;

select COLUMN_KEY, sf_column_name, new_column_name, NEW_DATA_TYPE
FROM MS_RAW.DBT_META.NEW_DATETIME_COLUMNS
WHERE COLUMN_KEY IN (SELECT COLUMN_KEY 
                     FROM MS_RAW.DBT_META.NEW_DATETIME_COLUMNS 
                     GROUP BY 1
                     HAVING COUNT(*) > 1)
ORDER BY ALL;


