CREATE SCHEMA IF NOT EXISTS MS_RAW.STG_META
;

---------------------------------------------

CREATE OR REPLACE TABLE MS_RAW.STG_META.SF_TABLES AS
WITH SF_TABLES AS (
        SELECT
            TABLE_SCHEMA,
            TABLE_NAME
        FROM ROL_RAW.INFORMATION_SCHEMA.TABLES
        WHERE TABLE_SCHEMA IN ('REEDONLINE_DBO', 
                               'REEDONLINE_DUPLICATEJOBSERVICE', 
                               'REEDONLINE_JOBIMPORT', 
                               'REEDONLINE_JOBS', 
                               'REEDONLINE_RECRUITERJOBSTEXTKERNEL')
          AND TABLE_TYPE = 'BASE TABLE'
          AND TABLE_NAME NOT LIKE '_DLT%'
        ORDER BY ALL
)
SELECT
    SF_TABLES.TABLE_SCHEMA AS SF_SCHEMA_NAME,
    SF_TABLES.TABLE_NAME   AS SF_TABLE_NAME,
    MS_TABLES.TABLE_SCHEMA AS MS_SCHEMA_NAME,
    MS_TABLES.TABLE_NAME   AS MS_TABLE_NAME,
    NULL::TEXT             AS NEW_TABLE_NAME
FROM ROL_RAW.REEDONLINE_META.TABLES MS_TABLES
INNER JOIN SF_TABLES
    ON REPLACE(REPLACE(SF_TABLES.TABLE_SCHEMA || '.' || SF_TABLES.TABLE_NAME, '_', ''), 'REEDONLINE', '')
       = UPPER(REPLACE(MS_TABLES.TABLE_SCHEMA || '.' || MS_TABLES.TABLE_NAME, '_', ''))
ORDER BY ALL
;

UPDATE MS_RAW.STG_META.SF_TABLES
   SET NEW_TABLE_NAME =
       REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
               REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
               REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
               REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
               REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
               REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
               REPLACE(REPLACE(REPLACE(
               '^'||SF_TABLE_NAME||'$'
              ,'JOB','RECRUITER_JOB')
              ,'ECRUITER','RECRUITER')
              ,'RRECRUITER','RECRUITER')
              ,'CANDIDATETOOLSACTIONLOOKUP','CANDIDATE_TOOLS_ACTION')
              ,'BANK_HOLIDAY_DATES','BANK_HOLIDAY_DATE')
              ,'CHECKOUT_METHODS','CHECKOUT_METHOD')
              ,'DUPLICATE_JOBS','DUPLICATE_JOB')
              ,'IN_ARREARS_JOB_SPENDS','IN_ARREARS_JOB_SPEND')
              ,'JOB_APPLICATIONS','JOB_APPLICATION')
              ,'JOB_POSTING_METHODS','JOB_POSTING_METHOD')
              ,'JOB_SECTORS','JOB_SECTOR')
              ,'JOB_VIEWS','JOB_VIEW')
              ,'LANGUAGES','LANGUAGE')
              ,'NATIONALITIES','NATIONALITY')
              ,'NOTICE_PERIODS','NOTICE_PERIOD')
              ,'ORDERS','ORDER')
              ,'OU_KEY_DOMAINS','OU_KEY_DOMAIN')
              ,'RECRUITER_FEEDBACK_LOOKUP','ECRUITER_FEEDBACK_TYPE')
              ,'SALARY_TYPE_JOBS','SALARY_TYPE_JOB')
              ,'SAVED_CANDIDATE_LISTS','SAVED_CANDIDATE_LIST')
              ,'SAVED_CANDIDATE_LIST_ENTRIES','SAVED_CANDIDATE_LIST_ENTRY')
              ,'SAVED_CANDIDATE_SEARCHES','SAVED_CANDIDATE_SEARCH')
              ,'SAVED_JOB_SEARCHES','SAVED_JOB_SEARCHE')
              ,'SKILLS_LANG_PROFICIENCY','SKILL_LANG_PROFICIENCY')
              ,'TRANSACTIONS','TRANSACTION')
              ,'USERS_EXTERNAL_FEED_FACT','USERS_EXTERNAL_FEED_TYPE')
              ,'^LOOKUP_','')
              ,'^JOBS','JOB')
              ,'_FACT$','')
              ,'_FACT_FK$','')
              ,'_LOOKUP$','')
              ,'_TYPES$','_TYPE')
              ,'^','')
              ,'$','') 
;

SELECT * FROM MS_RAW.STG_META.SF_TABLES
WHERE NEW_TABLE_NAME IN (
        SELECT NEW_TABLE_NAME
        FROM MS_RAW.STG_META.SF_TABLES
        GROUP BY 1
        HAVING COUNT(*) > 1
)
ORDER BY NEW_TABLE_NAME;

----------------------------------------

CREATE OR REPLACE TABLE MS_RAW.STG_META.SF_COLUMNS AS
SELECT
    SF_TABLES.*,
    MS_COLUMNS.COLUMN_NAME AS MS_COLUMN_NAME,
    SF_COLUMNS.COLUMN_NAME AS SF_COLUMN_NAME,
    NULL::STRING           AS BASE_COLUMN_NAME,
    NULL::STRING           AS NEW_COLUMN_NAME,
    NULL::STRING           AS NEW_COLUMN_TYPE,
    SF_COLUMNS.DATA_TYPE,
    SF_COLUMNS.CHARACTER_MAXIMUM_LENGTH,
    SF_COLUMNS.NUMERIC_PRECISION,
    SF_COLUMNS.NUMERIC_SCALE,
    SF_COLUMNS.DATETIME_PRECISION,
FROM ROL_RAW.INFORMATION_SCHEMA.COLUMNS AS SF_COLUMNS
INNER JOIN MS_RAW.STG_META.SF_TABLES AS SF_TABLES
    ON SF_COLUMNS.TABLE_SCHEMA = SF_TABLES.SF_SCHEMA_NAME
   AND SF_COLUMNS.TABLE_NAME   = SF_TABLES.SF_TABLE_NAME
INNER JOIN ROL_RAW.REEDONLINE_META.COLUMNS AS MS_COLUMNS
    ON MS_COLUMNS.TABLE_SCHEMA = SF_TABLES.MS_SCHEMA_NAME
   AND MS_COLUMNS.TABLE_NAME   = SF_TABLES.MS_TABLE_NAME
   AND UPPER(REPLACE(MS_COLUMNS.COLUMN_NAME, '_', '')) = REPLACE(SF_COLUMNS.COLUMN_NAME, '_', '')
;
