CREATE OR REPLACE TABLE MS_RAW.STG_META.SF_TABLES AS
WITH SF_TABLES AS (
        SELECT
            TABLE_SCHEMA,
            TABLE_NAME
        FROM ROL_RAW.INFORMATION_SCHEMA.TABLES
        WHERE TABLE_SCHEMA IN ('REEDONLINE_DBO', 
                               'REEDONLINE_DUPLICATEJOBSERVICE', 
                               'REEDONLINE_JOBIMPORT', 
                               'REEDONLINE_JOBS', 
                               'REEDONLINE_RECRUITERJOBSTEXTKERNEL')
          AND TABLE_TYPE = 'BASE TABLE'
          AND TABLE_NAME NOT LIKE '_DLT%'
        ORDER BY ALL
)
SELECT
    SF_TABLES.TABLE_SCHEMA AS SF_TABLE_SCHEMA,
    SF_TABLES.TABLE_NAME   AS SF_TABLE_NAME,
    MS_TABLES.TABLE_SCHEMA AS MS_TABLE_SCHEMA,
    MS_TABLES.TABLE_NAME   AS MS_TABLE_NAME,
    NULL::TEXT             AS NEW_TABLE_NAME
FROM ROL_RAW.REEDONLINE_META.TABLES MS_TABLES
INNER JOIN SF_TABLES
    ON REPLACE(REPLACE(SF_TABLES.TABLE_SCHEMA || '.' || SF_TABLES.TABLE_NAME, '_', ''), 'REEDONLINE', '')
       = UPPER(REPLACE(MS_TABLES.TABLE_SCHEMA || '.' || MS_TABLES.TABLE_NAME, '_', ''))
ORDER BY ALL
;

UPDATE MS_RAW.STG_META.SF_TABLES
   SET NEW_TABLE_NAME =
       REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
               REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
               REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
               REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
               REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
               REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
               REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
               '^'||SF_TABLE_NAME||'$'
              ,'^JOB$','RECRUITER_JOB')
              ,'CANDIDATETOOLSACTIONLOOKUP','CANDIDATE_TOOLS_ACTION')
              ,'BANK_HOLIDAY_DATES','BANK_HOLIDAY_DATE')
              ,'CHECKOUT_METHODS','CHECKOUT_METHOD')
              ,'DUPLICATE_JOBS','DUPLICATE_JOB')
              ,'EMAIL_FACT','EMAIL_LOG_TYPE')
              ,'EMAIL_TEMPLATE_ACTION_FACT','EMAIL_ACTION')
              ,'IN_ARREARS_JOB_SPENDS','IN_ARREARS_JOB_SPEND')
              ,'JOB_APPLICATIONS','JOB_APPLICATION')
              ,'JOB_POSTING_METHODS','JOB_POSTING_METHOD')
              ,'JOB_SECTORS','JOB_SECTOR')
              ,'JOB_VIEWS','JOB_VIEW')
              ,'JOBS','JOB')
              ,'LANGUAGES','LANGUAGE')
              ,'NATIONALITIES','NATIONALITY')
              ,'NOTICE_PERIODS','NOTICE_PERIOD')
              ,'ORDERS','ORDER')
              ,'OU_KEY_DOMAINS','OU_KEY_DOMAIN')
              ,'ECRUITER_FEEDBACK_LOOKUP','ECRUITER_FEEDBACK_TYPE')
              ,'SALARY_TYPE_JOBS','SALARY_TYPE_JOB')
              ,'SAVED_CANDIDATE_LISTS','SAVED_CANDIDATE_LIST')
              ,'SAVED_CANDIDATE_LIST_ENTRIES','SAVED_CANDIDATE_LIST_ENTRY')
              ,'SAVED_CANDIDATE_SEARCHES','SAVED_CANDIDATE_SEARCH')
              ,'SAVED_JOB_SEARCHES','SAVED_JOB_SEARCHE')
              ,'SKILLS_LANG_PROFICIENCY','SKILL_LANG_PROFICIENCY')
              ,'TRANSACTIONS','TRANSACTION')
              ,'USERS_EXTERNAL_FEED_FACT','USERS_EXTERNAL_FEED_TYPE')
              ,'ECRUITER','RECRUITER')
              ,'RRECRUITER','RECRUITER')
              ,'^LOOKUP_','')
              ,'_FACT$','')
              ,'_FACT_FK$','')
              ,'_LOOKUP$','')
              ,'_TYPES$','_TYPE')
              ,'^','')
              ,'$','') 
;

-- Check for duplicate NEW_TABLE -> must return NO Results
SELECT * FROM MS_RAW.STG_META.SF_TABLES
WHERE NEW_TABLE_NAME IN (
        SELECT NEW_TABLE_NAME
        FROM MS_RAW.STG_META.SF_TABLES
        GROUP BY 1
        HAVING COUNT(*) > 1
)
ORDER BY NEW_TABLE_NAME;

-- TEST NAMES
SELECT SF_TABLE_NAME, NEW_TABLE_NAME , SF_TABLE_SCHEMA
FROM MS_RAW.STG_META.SF_TABLES
WHERE 1 = 1
  AND SF_TABLE_NAME != NEW_TABLE_NAME
ORDER BY NEW_TABLE_NAME;