CREATE OR REPLACE TABLE MS_RAW.STG_META.SF_COLUMNS AS
SELECT
    SF_TABLES.*,
    MS_INFO_COLUMNS.COLUMN_NAME AS MS_COLUMN_NAME,
    SF_INFO_COLUMNS.COLUMN_NAME AS SF_COLUMN_NAME,
    NULL::STRING           AS BASE_COLUMN_NAME,
    NULL::STRING           AS NEW_COLUMN_NAME,
    NULL::STRING           AS NEW_COLUMN_TYPE,
    NULL::BOOLEAN          AS IS_PRIMARY_KEY,
    NULL::STRING           AS NEW_PRIMARY,
    NULL::BOOLEAN          AS IS_FOREIGN_KEY,
    NULL::STRING           AS NEW_FOREIGN_KEY,
    SF_INFO_COLUMNS.DATA_TYPE,
    SF_INFO_COLUMNS.CHARACTER_MAXIMUM_LENGTH,
    SF_INFO_COLUMNS.NUMERIC_PRECISION,
    SF_INFO_COLUMNS.NUMERIC_SCALE,
    SF_INFO_COLUMNS.DATETIME_PRECISION,
FROM ROL_RAW.INFORMATION_SCHEMA.COLUMNS AS SF_INFO_COLUMNS
INNER JOIN MS_RAW.STG_META.SF_TABLES AS SF_TABLES
    ON SF_INFO_COLUMNS.TABLE_SCHEMA = SF_TABLES.SF_TABLE_SCHEMA
   AND SF_INFO_COLUMNS.TABLE_NAME   = SF_TABLES.SF_TABLE_NAME
INNER JOIN ROL_RAW.REEDONLINE_META.COLUMNS AS MS_INFO_COLUMNS
    ON MS_INFO_COLUMNS.TABLE_SCHEMA = SF_TABLES.MS_TABLE_SCHEMA
   AND MS_INFO_COLUMNS.TABLE_NAME   = SF_TABLES.MS_TABLE_NAME
   AND UPPER(REPLACE(MS_INFO_COLUMNS.COLUMN_NAME, '_', '')) = REPLACE(SF_INFO_COLUMNS.COLUMN_NAME, '_', '')
;