CREATE OR REPLACE TRANSIENT TABLE MS_RAW.STG_META.T_PRIMARY_KEYS AS
    SELECT
        sfc.SF_TABLE_SCHEMA,
        sfc.SF_TABLE_NAME,
        sfc.SF_COLUMN_NAME,
        sfc.MS_TABLE_SCHEMA,
        sfc.MS_TABLE_NAME,
        sfc.MS_COLUMN_NAME,
        sft.NEW_TABLE_NAME,
        sft.NEW_TABLE_NAME || '_ID' AS NEW_TABLE_NAME_ID,
        sfc.NEW_COLUMN_NAME,
        kcu.CONSTRAINT_SCHEMA,
        kcu.CONSTRAINT_NAME,
        kcu.TABLE_NAME AS CONSTRAINT_TABLE_NAME,
        COUNT(*) OVER (PARTITION BY kcu.CONSTRAINT_SCHEMA, kcu.CONSTRAINT_NAME) AS PK_COLUMNS,
        COUNT(DISTINCT kcu.CONSTRAINT_SCHEMA, kcu.CONSTRAINT_NAME) OVER (PARTITION BY sfc.SF_TABLE_SCHEMA, sfc.SF_COLUMN_NAME) AS PK_TABLES,
        kcu.ORDINAL_POSITION
    FROM ROL_RAW.REEDONLINE_META.TABLE_CONSTRAINTS tc
    INNER JOIN ROL_RAW.REEDONLINE_META.KEY_COLUMN_USAGE kcu
        ON  kcu.TABLE_SCHEMA    = tc.TABLE_SCHEMA
        AND kcu.TABLE_NAME      = tc.TABLE_NAME
        AND kcu.CONSTRAINT_NAME = tc.CONSTRAINT_NAME
    INNER JOIN MS_RAW.STG_META.SF_COLUMNS sfc
        ON  kcu.TABLE_SCHEMA = sfc.MS_TABLE_SCHEMA
        AND kcu.TABLE_NAME   = sfc.MS_TABLE_NAME
        AND kcu.COLUMN_NAME  = sfc.MS_COLUMN_NAME
    INNER JOIN MS_RAW.STG_META.SF_TABLES sft
        ON sfc.SF_TABLE_SCHEMA = sft.SF_TABLE_SCHEMA
       AND sfc.SF_TABLE_NAME   = sft.SF_TABLE_NAME
    WHERE tc.CONSTRAINT_TYPE = 'PRIMARY KEY'
      AND sfc.SF_TABLE_NAME != 'PRICEBOOK_ENTRY' -- pk has 5 columns
     ORDER BY sfc.SF_TABLE_SCHEMA, sfc.SF_COLUMN_NAME;

    -- 298 PKEYS, 320 PK Columns
    SELECT count(distinct CONSTRAINT_SCHEMA, CONSTRAINT_NAME) as TOTAL_PKEYS
         , count(*) AS TOTAL_COLUMNS
    FROM MS_RAW.STG_META.T_PRIMARY_KEYS;

    -- 276 PKEYS, 276 PK Columns
    SELECT count(distinct CONSTRAINT_SCHEMA, CONSTRAINT_NAME) as TOTAL_PKEYS
         , count(*) AS TOTAL_COLUMNS
    FROM MS_RAW.STG_META.T_PRIMARY_KEYS
    WHERE PK_COLUMNS = 1;

    --  22 PKEYS, 44 PK Columns
    SELECT count(distinct CONSTRAINT_SCHEMA, CONSTRAINT_NAME) as TOTAL_PKEYS
         , count(*) AS TOTAL_COLUMNS
    FROM MS_RAW.STG_META.T_PRIMARY_KEYS
    WHERE PK_COLUMNS = 2;

------------------------- PK_COLUMNS = 2 <START> ----------------------------------

    CREATE OR REPLACE VIEW MS_RAW.STG_META.V_PRIMARY_KEYS_TWO AS
    WITH TWO_COLUMNS AS (
        SELECT sft.SF_TABLE_SCHEMA, 
               sft.SF_TABLE_NAME, 
               FIRST_VALUE(sfc.NEW_COLUMN_NAME)  
                    OVER (PARTITION BY sft.SF_TABLE_SCHEMA, sft.SF_TABLE_NAME ORDER BY pk.ordinal_position) 
                                           AS KEY_PART_1,
               LAST_VALUE(sfc.NEW_COLUMN_NAME)  
                    OVER (PARTITION BY sft.SF_TABLE_SCHEMA, sft.SF_TABLE_NAME ORDER BY pk.ordinal_position) 
                                          AS KEY_PART_2,
               KEY_PART_1 || ' * 10^12 + ' || KEY_PART_2
                                          AS NEW_PRIMARY_KEY_EXPRESSION,
               KEY_PART_1 || ',' || KEY_PART_2
                                          AS NEW_PRIMARY_KEY_UNIQUE_COLUMNS,
               
        FROM MS_RAW.STG_META.T_PRIMARY_KEYS pk
        INNER JOIN MS_RAW.STG_META.SF_COLUMNS sfc
            ON  pk.SF_TABLE_SCHEMA = sfc.SF_TABLE_SCHEMA
            AND pk.SF_TABLE_NAME   = sfc.SF_TABLE_NAME
            AND pk.SF_COLUMN_NAME  = sfc.SF_COLUMN_NAME
        INNER JOIN MS_RAW.STG_META.SF_TABLES sft
            ON  sft.SF_TABLE_SCHEMA = sfc.SF_TABLE_SCHEMA
            AND sft.SF_TABLE_NAME   = sfc.SF_TABLE_NAME
        WHERE pk.PK_COLUMNS = 2
    )
    SELECT SF_TABLE_SCHEMA, 
           SF_TABLE_NAME, 
           NEW_PRIMARY_KEY_EXPRESSION,
           NEW_PRIMARY_KEY_UNIQUE_COLUMNS
    FROM TWO_COLUMNS
    GROUP BY ALL
    ORDER BY ALL
    ;

    -- 22
    SELECT * FROM MS_RAW.STG_META.V_PRIMARY_KEYS_TWO 
    ORDER BY ALL;

    -- 22
    UPDATE MS_RAW.STG_META.SF_TABLES AS t
       SET PRIMARY_KEY_NAME     = NEW_TABLE_NAME || '_ID',
           PK_COLUMNS           = 2,
           PK_TABLES            = 1,
           NEW_PRIMARY_KEY_NAME = NEW_TABLE_NAME || '_ID',
           NEW_PRIMARY_KEY_EXPRESSION = pk2.NEW_PRIMARY_KEY_EXPRESSION,
           NEW_PRIMARY_KEY_UNIQUE_COLUMNS = pk2.NEW_PRIMARY_KEY_UNIQUE_COLUMNS
      FROM MS_RAW.STG_META.V_PRIMARY_KEYS_TWO AS pk2
      WHERE t.sf_table_schema = pk2.sf_table_schema
        AND t.sf_table_name   = pk2.sf_table_name
    ;

    -- 1 
    UPDATE MS_RAW.STG_META.SF_TABLES AS t
       SET PK_COLUMNS           = 1,
           NEW_PRIMARY_KEY_EXPRESSION = NULL
      FROM MS_RAW.STG_META.V_PRIMARY_KEYS_TWO AS pk2
      WHERE t.sf_table_name   = 'RATE_CARD_TIER'
    ;
    -- 44
    DELETE FROM MS_RAW.STG_META.T_PRIMARY_KEYS
    WHERE PK_COLUMNS = 2;

------------------------- PK_COLUMNS = 2 <END> ----------------------------------


    -- 276 PKEYS, 276 PK Columns
    SELECT count(distinct CONSTRAINT_SCHEMA, CONSTRAINT_NAME) as TOTAL_PKEYS
         , count(*) AS TOTAL_COLUMNS
    FROM MS_RAW.STG_META.T_PRIMARY_KEYS
    ;

    -- 224 PKEYS, 224 PK Columns -> PK = TABLE+_ID
    SELECT count(distinct CONSTRAINT_SCHEMA, CONSTRAINT_NAME) as TOTAL_PKEYS
         , count(*) AS TOTAL_COLUMNS
    FROM MS_RAW.STG_META.T_PRIMARY_KEYS K
    WHERE NEW_TABLE_NAME_ID = NEW_COLUMN_NAME
    ;

    
    -- 12 PKEYS, 12 PK Columns -> PK != TABLE+_ID but in previous PK = TABLE+_ID
    SELECT count(distinct CONSTRAINT_SCHEMA, CONSTRAINT_NAME) as TOTAL_PKEYS
         , count(*) AS TOTAL_COLUMNS
    FROM MS_RAW.STG_META.T_PRIMARY_KEYS K
    WHERE NEW_TABLE_NAME_ID != NEW_COLUMN_NAME
      AND (SF_TABLE_SCHEMA, SF_COLUMN_NAME) IN (SELECT SF_TABLE_SCHEMA, SF_COLUMN_NAME
                                                FROM MS_RAW.STG_META.T_PRIMARY_KEYS
                                                WHERE NEW_TABLE_NAME_ID = NEW_COLUMN_NAME)        
    ;
    
    -- 40 PKEYS, 40 PK Columns -> PK != TABLE+_ID an not in previous PK = TABLE+_ID
    SELECT count(distinct CONSTRAINT_SCHEMA, CONSTRAINT_NAME) as TOTAL_PKEYS
         , count(*) AS TOTAL_COLUMNS
    FROM MS_RAW.STG_META.T_PRIMARY_KEYS K
    WHERE NEW_TABLE_NAME_ID != NEW_COLUMN_NAME
      AND (SF_TABLE_SCHEMA, SF_COLUMN_NAME) NOT IN (SELECT SF_TABLE_SCHEMA, SF_COLUMN_NAME
                                                    FROM MS_RAW.STG_META.T_PRIMARY_KEYS
                                                    WHERE NEW_TABLE_NAME_ID = NEW_COLUMN_NAME)        
    ;

    
    -- 56 (PK_COLUMNS=1 & PK_TABLES>1)
    SELECT count(distinct CONSTRAINT_SCHEMA, CONSTRAINT_NAME) as TOTAL_PKEYS
    FROM MS_RAW.STG_META.T_PRIMARY_KEYS
    WHERE PK_TABLES > 1;
    
   
  ----------- PK_COLUMNS = 1  AND NEW_TABLE_NAME_ID = NEW_COLUMN_NAME <START> ----------------

    CREATE OR REPLACE VIEW MS_RAW.STG_META.V_PRIMARY_KEYS_TABLE_ID AS
    SELECT SF_TABLE_SCHEMA, 
           SF_TABLE_NAME, 
           SF_COLUMN_NAME, 
           NEW_TABLE_NAME, 
           NEW_COLUMN_NAME,
           NEW_TABLE_NAME_ID,
           PK_TABLES,
    FROM MS_RAW.STG_META.T_PRIMARY_KEYS K
    WHERE NEW_TABLE_NAME_ID = NEW_COLUMN_NAME
    ORDER BY SF_TABLE_SCHEMA, NEW_TABLE_NAME; 

    -- 224
    SELECT * FROM MS_RAW.STG_META.V_PRIMARY_KEYS_TABLE_ID ORDER BY ALL;

    -- 224
    UPDATE MS_RAW.STG_META.SF_TABLES AS t
       SET PRIMARY_KEY_NAME     = pk2.SF_COLUMN_NAME,
           PK_COLUMNS           = 1,
           PK_TABLES            = pk2.PK_TABLES,
           NEW_PRIMARY_KEY_NAME = pk2.NEW_TABLE_NAME_ID
      FROM MS_RAW.STG_META.V_PRIMARY_KEYS_TABLE_ID AS pk2
      WHERE t.sf_table_schema = pk2.sf_table_schema
        AND t.sf_table_name   = pk2.sf_table_name
    ;
  
    -- 224 
    DELETE FROM MS_RAW.STG_META.T_PRIMARY_KEYS
    WHERE NEW_TABLE_NAME_ID = NEW_COLUMN_NAME
    ;

    ----------- pk.PK_TABLES > 1
    -- 12
    CREATE OR REPLACE VIEW MS_RAW.STG_META.V_PRIMARY_KEYS_TABLE_ID_MANY AS
    SELECT pk.SF_TABLE_SCHEMA, 
           pk.SF_TABLE_NAME, 
           pk.SF_COLUMN_NAME, 
           pk.NEW_TABLE_NAME, 
           pk.NEW_COLUMN_NAME,
           pk.NEW_TABLE_NAME_ID,
           pk.PK_TABLES,
           t.SF_TABLE_NAME as TABLE_NAME,
           t.NEW_PRIMARY_KEY_NAME
    FROM MS_RAW.STG_META.T_PRIMARY_KEYS AS pk
    INNER JOIN MS_RAW.STG_META.SF_TABLES AS t
        ON t.SF_TABLE_SCHEMA      = pk.SF_TABLE_SCHEMA
       AND t.NEW_PRIMARY_KEY_NAME = pk.NEW_COLUMN_NAME
       AND t.NEW_PRIMARY_KEY_NAME = T.NEW_TABLE_NAME || '_ID'
    WHERE pk.NEW_TABLE_NAME_ID != pk.NEW_COLUMN_NAME
      AND pk.PK_TABLES > 1
    ORDER BY pk.SF_TABLE_SCHEMA, pk.SF_TABLE_NAME, pk.NEW_TABLE_NAME;

    -- 12
    SELECT count(*), count(distinct sf_table_schema, sf_table_name)
      FROM MS_RAW.STG_META.V_PRIMARY_KEYS_TABLE_ID_MANY 
    ORDER BY NEW_COLUMN_NAME;

    -- 12
    UPDATE MS_RAW.STG_META.SF_TABLES AS t
       SET PRIMARY_KEY_NAME     = SF_COLUMN_NAME,
           PK_COLUMNS           = 1,
           PK_TABLES            = pk2.PK_TABLES,
           NEW_PRIMARY_KEY_NAME = NEW_COLUMN_NAME
      FROM MS_RAW.STG_META.V_PRIMARY_KEYS_TABLE_ID_MANY AS pk2
      WHERE t.sf_table_schema = pk2.sf_table_schema
        AND t.sf_table_name   = pk2.sf_table_name
    ;
  
    -- 12
    DELETE FROM MS_RAW.STG_META.T_PRIMARY_KEYS
    WHERE (sf_table_schema, sf_table_name)
       in (select sf_table_schema, sf_table_name from MS_RAW.STG_META.V_PRIMARY_KEYS_TABLE_ID_MANY)
    ;

  ----------- PK_COLUMNS = 1  AND NEW_TABLE_NAME_ID = NEW_COLUMN_NAME <END> ----------------
  ----------- PK_COLUMNS = 1  AND NEW_TABLE_NAME_ID != NEW_COLUMN_NAME <START> ----------------
    -- 40
    SELECT * FROM MS_RAW.STG_META.T_PRIMARY_KEYS 
    ORDER BY NEW_COLUMN_NAME;

    -- 40
    SELECT * FROM MS_RAW.STG_META.T_PRIMARY_KEYS 
    WHERE NEW_COLUMN_NAME != NEW_TABLE_NAME_ID
    ORDER BY NEW_COLUMN_NAME;

    -- 40
    UPDATE MS_RAW.STG_META.SF_TABLES AS t
     SET PRIMARY_KEY_NAME     = pk2.SF_COLUMN_NAME,
         PK_COLUMNS           = 1,
         PK_TABLES            = pk2.PK_TABLES,
         NEW_PRIMARY_KEY_NAME = pk2.NEW_TABLE_NAME_ID
    FROM MS_RAW.STG_META.T_PRIMARY_KEYS AS pk2
    WHERE t.sf_table_schema = pk2.sf_table_schema
      AND t.sf_table_name   = pk2.sf_table_name
    ;

    ----------- START  PK_COLUMNS = 1  AND NEW_TABLE_NAME_ID != NEW_COLUMN_NAME <END> ----------------

-- EMPTY   
SELECT *
FROM MS_RAW.STG_META.SF_TABLES
WHERE SF_TABLE_NAME != 'PRICEBOOK_ENTRY'
  AND PRIMARY_KEY_NAME IS NULL
ORDER BY ALL
;

-- STATS FROM PK IN SF_TABLES
SELECT COUNT(*),                                                  --298
       COUNT(CASE WHEN PK_COLUMNS  = 1 THEN 1 END) AS ONE_COLUMN, --277
       COUNT(CASE WHEN PK_COLUMNS != 1 THEN 1 END) AS TWO_COLUMN, -- 21
       COUNT(CASE WHEN PRIMARY_KEY_NAME IS NULL THEN 1 END) AS NO_PRIMARY_KEY_NAME, -- 0
       COUNT(CASE WHEN (NEW_TABLE_NAME IS NULL OR NEW_PRIMARY_KEY_NAME IS NULL) THEN 1 END) AS NO_NEW, -- 0
       COUNT(CASE WHEN ENDSWITH(NEW_PRIMARY_KEY_NAME,'_ID')                     THEN 1 END) AS ENDSWITH_ID,              -- 298
       COUNT(CASE WHEN NEW_TABLE_NAME || '_ID'  = NEW_PRIMARY_KEY_NAME                     THEN 1 END) AS MASTER_PKS,    -- 286
       COUNT(CASE WHEN NEW_TABLE_NAME || '_ID'  = NEW_PRIMARY_KEY_NAME AND PK_COLUMNS != 1 THEN 1 END) AS MASTER_PKS2,   --  21
       COUNT(CASE WHEN NEW_TABLE_NAME || '_ID'  = NEW_PRIMARY_KEY_NAME AND PK_COLUMNS  = 1 THEN 1 END) AS MASTER_PKS1,   -- 265 
       COUNT(CASE WHEN NEW_TABLE_NAME || '_ID' != NEW_PRIMARY_KEY_NAME                     THEN 1 END) AS SECONDARY_PKS1,--  12
FROM MS_RAW.STG_META.SF_TABLES
WHERE SF_TABLE_NAME != 'PRICEBOOK_ENTRY'
;

-- STATS FROM PK IN SF_TABLES where sft.PK_COLUMNS = 1 
SELECT COUNT(*), -- 277
       COUNT(CASE WHEN ENDSWITH(sft.NEW_PRIMARY_KEY_NAME,'_ID')                                        THEN 1 END) AS ENDSWITH_ID,   -- 277
       COUNT(CASE WHEN sft.NEW_TABLE_NAME || '_ID'  = sft.NEW_PRIMARY_KEY_NAME                         THEN 1 END) AS MASTER_PKS,    -- 265
       COUNT(CASE WHEN sft.NEW_TABLE_NAME || '_ID' != sft.NEW_PRIMARY_KEY_NAME                         THEN 1 END) AS SECONDARY_PKS1,--  12
FROM MS_RAW.STG_META.SF_TABLES sft
INNER JOIN MS_RAW.STG_META.SF_COLUMNS sfc
   ON sft.SF_TABLE_SCHEMA  = sfc.SF_TABLE_SCHEMA
  AND sft.SF_TABLE_NAME    = sfc.SF_TABLE_NAME
  AND sft.PRIMARY_KEY_NAME = sfc.SF_COLUMN_NAME
WHERE sft.SF_TABLE_NAME != 'PRICEBOOK_ENTRY'
  AND sft.PK_COLUMNS = 1 
;

-- STATS FROM PK IN SF_TABLES where sft.PK_COLUMNS = 2 
SELECT COUNT(*), -- 21
       COUNT(CASE WHEN sft.NEW_TABLE_NAME || '_ID'  = sft.NEW_PRIMARY_KEY_NAME                         THEN 1 END) AS MASTER_PKS,    -- 21
FROM MS_RAW.STG_META.SF_TABLES sft
WHERE sft.PK_COLUMNS = 2 
;


???????????????? TO INSERT THE NEW COLUMNS IN SF_COLUMNS >>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- STATS FROM PK IN SF_TABLES where sft.PK_COLUMNS = 2 
SELECT COUNT(*), -- 0
       COUNT(CASE WHEN sft.NEW_TABLE_NAME || '_ID'  = sft.NEW_PRIMARY_KEY_NAME                         THEN 1 END) AS MASTER_PKS,    -- 21
FROM MS_RAW.STG_META.SF_TABLES sft
INNER JOIN MS_RAW.STG_META.SF_COLUMNS sfc
   ON sft.SF_TABLE_SCHEMA  = sfc.SF_TABLE_SCHEMA
  AND sft.SF_TABLE_NAME    = sfc.SF_TABLE_NAME
  AND sft.PRIMARY_KEY_NAME = sfc.SF_COLUMN_NAME
WHERE sft.PK_COLUMNS = 2 
;
