    CREATE OR REPLACE VIEW MS_RAW.STG_META.V_PRIMARY_KEYS AS
    SELECT
        sfc.SF_TABLE_SCHEMA,
        sfc.SF_TABLE_NAME,
        sfc.SF_COLUMN_NAME,
        sfc.MS_TABLE_SCHEMA,
        sfc.MS_TABLE_NAME,
        sfc.MS_COLUMN_NAME,
        kcu.CONSTRAINT_NAME,
        COUNT(SF_COLUMN_NAME) OVER (PARTITION BY sfc.SF_TABLE_SCHEMA, sfc.SF_TABLE_NAME) AS PK_COLUMNS,
        kcu.ORDINAL_POSITION
    FROM ROL_RAW.REEDONLINE_META.TABLE_CONSTRAINTS tc
    INNER JOIN ROL_RAW.REEDONLINE_META.KEY_COLUMN_USAGE kcu
        ON  kcu.TABLE_SCHEMA    = tc.TABLE_SCHEMA
        AND kcu.TABLE_NAME      = tc.TABLE_NAME
        AND kcu.CONSTRAINT_NAME = tc.CONSTRAINT_NAME
    INNER JOIN MS_RAW.STG_META.SF_COLUMNS sfc
        ON  kcu.TABLE_SCHEMA = sfc.MS_TABLE_SCHEMA
        AND kcu.TABLE_NAME   = sfc.MS_TABLE_NAME
        AND kcu.COLUMN_NAME  = sfc.MS_COLUMN_NAME
    WHERE tc.CONSTRAINT_TYPE = 'PRIMARY KEY'
    ORDER BY ALL;


    SELECT K.SF_TABLE_SCHEMA, 
           K.SF_TABLE_NAME, 
           T.NEW_TABLE_NAME, 
           K.SF_COLUMN_NAME, 
           T.NEW_TABLE_NAME || '_ID' AS NEW_PK_COLUMN_NAME,
           COUNT(*) OVER (PARTITION BY K.SF_TABLE_SCHEMA, K.SF_COLUMN_NAME) AS PK_TABLES,
           K.SF_COLUMN_NAME  = NEW_PK_COLUMN_NAME AS IS_TABLE_ID
    FROM MS_RAW.STG_META.V_PRIMARY_KEYS K
    INNER JOIN MS_RAW.STG_META.SF_TABLES T
        ON K.SF_TABLE_SCHEMA = T.SF_TABLE_SCHEMA
       AND K.SF_TABLE_NAME  = T.SF_TABLE_NAME
    WHERE K.PK_COLUMNS = 1
--      AND K.SF_COLUMN_NAME  = NEW_PK_COLUMN_NAME  -- 167
--      AND K.SF_COLUMN_NAME != NEW_PK_COLUMN_NAME  --  82      
    QUALIFY PK_TABLES = 1
    ORDER BY T.SF_TABLE_SCHEMA, T.NEW_TABLE_NAME; 

HOLIDAY_DATE_ID -> BANK_HOLIDAY_DATE_ID
LOOKUP_CANDIDATE_SEARCH_TYPES(SEARCH_TYPE)	-> CANDIDATE_SEARCH_TYPE_ID
LOOKUP_CANDIDATE_SEARCH_TYPES()

SELECT * FROM ROL_RAW.REEDONLINE_DBO.API_BULK_POSTER_LOG LIMIT 10;
-- ??? FK_NAME -> PK_NAME WILL SHOW THE RELATION BETWEEN FK=XXXX_ID AND PK=ID
-- 

    SELECT K.SF_TABLE_SCHEMA, K.SF_TABLE_NAME, T.NEW_TABLE_NAME, K.SF_COLUMN_NAME, T.NEW_TABLE_NAME || '_ID' AS NEW_PK_COLUMN_NAME,
           COUNT(*) OVER (PARTITION BY K.SF_TABLE_SCHEMA, K.SF_COLUMN_NAME) AS PK_TABLES
    FROM MS_RAW.STG_META.V_PRIMARY_KEYS K
    INNER JOIN MS_RAW.STG_META.SF_TABLES T
        ON K.SF_TABLE_SCHEMA = T.SF_TABLE_SCHEMA
       AND K.SF_TABLE_NAME   = T.SF_TABLE_NAME
    WHERE K.PK_COLUMNS = 1
      AND K.SF_COLUMN_NAME != NEW_PK_COLUMN_NAME
    QUALIFY COUNT(*) OVER (PARTITION BY K.SF_TABLE_SCHEMA, K.SF_COLUMN_NAME) > 1
    ORDER BY T.SF_TABLE_SCHEMA, K.SF_COLUMN_NAME, T.NEW_TABLE_NAME, T.SF_TABLE_NAME; 