UPDATE MS_RAW.STG_META.SF_TABLES
   SET NEW_TABLE_NAME = 'LANGUAGE_PROFICIENCY' WHERE SF_TABLE_NAME = 'LOOKUP_SKILLS_LANG_PROFICIENCY';
   
    CREATE OR REPLACE VIEW MS_RAW.STG_META.V_PRIMARY_KEYS AS
    SELECT
        sfc.SF_TABLE_SCHEMA,
        sfc.SF_TABLE_NAME,
        sfc.SF_COLUMN_NAME,
        sfc.MS_TABLE_SCHEMA,
        sfc.MS_TABLE_NAME,
        sfc.MS_COLUMN_NAME,
        sfc.NEW_COLUMN_NAME,
        sft.NEW_TABLE_NAME,
        kcu.CONSTRAINT_NAME,
        COUNT(SF_COLUMN_NAME) OVER (PARTITION BY sfc.SF_TABLE_SCHEMA, sfc.SF_TABLE_NAME) AS PK_COLUMNS,
        kcu.ORDINAL_POSITION
    FROM ROL_RAW.REEDONLINE_META.TABLE_CONSTRAINTS tc
    INNER JOIN ROL_RAW.REEDONLINE_META.KEY_COLUMN_USAGE kcu
        ON  kcu.TABLE_SCHEMA    = tc.TABLE_SCHEMA
        AND kcu.TABLE_NAME      = tc.TABLE_NAME
        AND kcu.CONSTRAINT_NAME = tc.CONSTRAINT_NAME
    INNER JOIN MS_RAW.STG_META.SF_COLUMNS sfc
        ON  kcu.TABLE_SCHEMA = sfc.MS_TABLE_SCHEMA
        AND kcu.TABLE_NAME   = sfc.MS_TABLE_NAME
        AND kcu.COLUMN_NAME  = sfc.MS_COLUMN_NAME
    INNER JOIN MS_RAW.STG_META.SF_TABLES sft
        ON sfc.SF_TABLE_SCHEMA = sft.SF_TABLE_SCHEMA
       AND sfc.SF_TABLE_NAME   = sft.SF_TABLE_NAME
    WHERE tc.CONSTRAINT_TYPE = 'PRIMARY KEY'
    ORDER BY ALL;

    -- 241 pk has one column
    CREATE OR REPLACE VIEW MS_RAW.STG_META.V_PRIMARY_KEYS_ONE AS
    SELECT SF_TABLE_SCHEMA, 
           SF_TABLE_NAME, 
           NEW_TABLE_NAME, 
           SF_COLUMN_NAME, 
           NEW_TABLE_NAME || '_ID' AS NEW_PK_COLUMN_NAME,
           COUNT(*) OVER (PARTITION BY SF_TABLE_SCHEMA, SF_COLUMN_NAME) AS PK_TABLES,
           SF_COLUMN_NAME = NEW_PK_COLUMN_NAME AS IS_TABLE_ID
    FROM MS_RAW.STG_META.V_PRIMARY_KEYS K
    WHERE PK_COLUMNS = 1
    ORDER BY SF_TABLE_SCHEMA, NEW_TABLE_NAME; 

    -- 207 pk = <table_name>_id
    SELECT *
    FROM MS_RAW.STG_META.V_PRIMARY_KEYS_ONE K
    WHERE SF_COLUMN_NAME = NEW_PK_COLUMN_NAME
    ; 

    -- 34 pk = <table_name>_id
    SELECT *
    FROM MS_RAW.STG_META.V_PRIMARY_KEYS_ONE K
    WHERE SF_COLUMN_NAME != NEW_PK_COLUMN_NAME
    ;

    -- INITIAL LOAD OF ONE PK COLUMN
    UPDATE MS_RAW.STG_META.SF_TABLES AS t
       SET PRIMARY_KEY_NAME = i.sf_column_name,
           PK_COLUMNS  = 1,
           NEW_PRIMARY_KEY_NAME = i.sf_column_name
      FROM MS_RAW.STG_META.V_PRIMARY_KEYS_ONE AS i
      WHERE t.sf_table_schema = i.sf_table_schema
        AND t.sf_table_name   = i.sf_table_name
    ;

    SELECT * FROM MS_RAW.STG_META.SF_TABLES  WHERE PK_COLUMNS  = 1 ORDER BY ALL;
    SELECT * FROM MS_RAW.STG_META.SF_TABLES  WHERE PRIMARY_KEY_NAME = 'SECTOR_ID';
    -- INVESTIGATE WHICH PK TO BE RENAMED
    SELECT i.sf_column_name,
           i.sf_table_name = c.sf_table_name as IS_PK,
           i.NEW_PK_COLUMN_NAME,
           c.sf_table_NAME,
           i.NEW_TABLE_NAME,
           c.sf_table_schema
      FROM MS_RAW.STG_META.SF_COLUMNS AS c
      INNER JOIN MS_RAW.STG_META.V_PRIMARY_KEYS_ONE AS i
          ON c.sf_table_schema = i.sf_table_schema
             and c.sf_table_name = i.sf_table_name
             and c.sf_column_name = i.sf_column_name
      WHERE 
         i.SF_COLUMN_NAME != i.NEW_PK_COLUMN_NAME
      -- TO KEEP
         AND    i.sf_column_name NOT IN ('API_TOKEN_ACCESS_LOG_ID','JOB_ID','OU_ID','PRODUCT_BASE_ID','CANDIDATE_ID','ECRUITER_ID','USER_ID','SALARY_TYPE_ID'
                                     )
      -- TO RENAME
         AND i.sf_column_name NOT IN ('CC_STATUS','CLIENT_ID','DISPLAY_STYLE_ID','DRAFT_ID','DUPLICATE_JOBS_ID','ECRUITER_FEEDBACK_ID','ECRUITER_FEEDBACK_TYPE_ID',
                                      'ENQUIRY_LOG_STATUS_ID','EMAIL_ACTION_ID','FEEDBACK_ID','GATEWAY_ID','HOLIDAY_DATE_ID','IMPORT_FEED_ECRUITER_ID','ID','IN_ARREARS_JOB_SPENDS_ID',
                                      'LOG_ID','JOB_SEARCH_ALERT_CHANNEL_LOOKUP_ID','JOB_SECTOR_VISIBILITY_BW','JOB_SPEND_REASON_BW','LEVEL_ID','LIST_ID','LOG_TYPE','NOTICE_ID',
                                      'ORG_ID','OU_BETA_ACCESS_BW','PROFICIENCY_ID','PROFILE_ID','PUSH_NOTIFICATION_PREFERENCE_BW','REG_TYPE_ID','SALARY_DESCRIPTION_BW',
                                      'SEARCH_ID','SEARCH_TYPE','SPENT_ON_TYPE_ID','TEMPLATE_ID','TYPE_ID','USER_ACCOUNT_BW','USER_JOB_HISTORY_ID'
                                     )
    ORDER BY ALL;

    SELECT i.sf_column_name,
           i.sf_table_name = c.sf_table_name as IS_PK,
           i.NEW_PK_COLUMN_NAME,
           c.sf_table_NAME,
           i.NEW_TABLE_NAME,
           c.sf_table_schema
      FROM MS_RAW.STG_META.SF_COLUMNS AS c
      INNER JOIN MS_RAW.STG_META.V_PRIMARY_KEYS_ONE AS i
          ON c.sf_table_schema = i.sf_table_schema
             and c.sf_column_name = i.sf_column_name
      WHERE 
          i.SF_COLUMN_NAME != i.NEW_PK_COLUMN_NAME
      -- TO KEEP
          AND i.sf_column_name NOT IN ('API_TOKEN_ACCESS_LOG_ID','JOB_ID','OU_ID','PRODUCT_BASE_ID')
    ORDER BY ALL;

    -- INITIAL LOAD OF ONE PK COLUMN
    UPDATE MS_RAW.STG_META.SF_TABLES AS t
       SET NEW_PRIMARY_KEY_NAME = i.NEW_PK_COLUMN_NAME
      FROM MS_RAW.STG_META.V_PRIMARY_KEYS_ONE AS i
      WHERE t.sf_table_schema = i.sf_table_schema
        AND t.sf_table_name   = i.sf_table_name
        AND i.sf_column_name NOT IN ('API_TOKEN_ACCESS_LOG_ID','JOB_ID','OU_ID','PRODUCT_BASE_ID')
    ;

   
    UPDATE MS_RAW.STG_META.SF_COLUMNS AS c
       SET NEW_COLUMN_NAME = t.NEW_PRIMARY_KEY_NAME
      FROM MS_RAW.STG_META.SF_TABLES AS t
      WHERE c.sf_column_name = t.PRIMARY_KEY_NAME
        AND t.PK_COLUMNS = 1
    ;

---------- NOW 2 COLUMNS


   -- CREATE OR REPLACE VIEW MS_RAW.STG_META.V_PRIMARY_KEYS_TWO AS
    SELECT pk.SF_TABLE_SCHEMA, 
           pk.SF_TABLE_NAME, 
           pk.NEW_TABLE_NAME, 
           pk.NEW_TABLE_NAME || '_ID' AS NEW_PK_COLUMN_NAME,
           pk.ORDINAL_POSITION,
           pk.SF_COLUMN_NAME,
           sfc.NEW_COLUMN_NAME
  --         MAX(CASE WHEN pk.ORDINAL_POSITION = 1 THEN sfc.NEW_COLUMN_NAME END) AS KEY_PART_1,
  --         MAX(CASE WHEN pk.ORDINAL_POSITION = 2 THEN sfc.NEW_COLUMN_NAME END) AS KEY_PART_2,
  --         KEY_PART_1 || ' * 10^12 + ' || KEY_PART_2                           AS NEW_PK_COLUMN_EXPRESSION
    FROM MS_RAW.STG_META.V_PRIMARY_KEYS pk
    INNER JOIN MS_RAW.STG_META.SF_COLUMNS sfc
        ON  pk.SF_TABLE_SCHEMA = sfc.SF_TABLE_SCHEMA
        AND pk.SF_TABLE_NAME   = sfc.SF_TABLE_NAME
        AND pk.SF_COLUMN_NAME  = sfc.SF_COLUMN_NAME
    WHERE pk.PK_COLUMNS = 2
      AND pk.SF_TABLE_NAME != 'PRICEBOOK_ENTRY'
    --GROUP BY ALL
    --  AND pk.ORDINAL_POSITION > 2
    ORDER BY ALL
    ;

    SELECT * FROM MS_RAW.STG_META.V_PRIMARY_KEYS 
     WHERE PK_COLUMNS = 2
       AND NEW_COLUMN_NAME IS NULL
    ORDER BY ALL;

    SELECT * FROM MS_RAW.STG_META.V_PRIMARY_KEYS WHERE SF_COLUMN_NAME='CANDIDATE_ID' AND PK_COLUMNS = 1;
    SELECT * FROM MS_RAW.STG_META.SF_TABLES WHERE PRIMARY_KEY_NAME='CANDIDATE_ID';

    CREATE TABLE MS_RAW.STG_META.NEW_COLUMN_NAMES (
        SF_TABLE_SCHEMA VARCHAR,
        SF_TABLE_NAME   VARCHAR,
        SF_COLUMN_NAME  VARCHAR,
        NEW_COLUMN_NAME VARCHAR
    );
    INSERT INTO MS_RAW.STG_META.NEW_COLUMN_NAMES
    VALUES (),
           ()
    ;
        
/*
    UPDATE MS_RAW.STG_META.SF_COLUMNS AS c
       SET NEW_COLUMN_NAME = t.NEW_PRIMARY_KEY_NAME
    WHERE (SF_TABLE_SCHEMA, SF_TABLE_NAME, SF_COLUMN_NAME) IN (
       SELECT NULL::STRING SF_TABLE_SCHEMA, NULL::STRING SF_TABLE_SCHEMA, NULL::STRING SF_COLUMN_NAME, NULL::STRING SF_COLUMN_NAME
       UNION ALL
       SELECT 'X','V','X'
    )
    ;
*/
    CREATE OR REPLACE VIEW MS_RAW.STG_META.V_PRIMARY_KEYS_TWO AS
    SELECT SF_TABLE_SCHEMA, 
           SF_TABLE_NAME, 
           NEW_TABLE_NAME, 
           NEW_TABLE_NAME || '_ID' AS NEW_PK_COLUMN_NAME,
           ORDINAL_POSITION,
           SF_COLUMN_NAME,
  --         MAX(CASE WHEN ORDINAL_POSITION = 1 THEN SF_COLUMN_NAME END) AS KEY_PART_1,
  --         MAX(CASE WHEN ORDINAL_POSITION = 2 THEN SF_COLUMN_NAME END) AS KEY_PART_2,
  --         (KEY_PART_1 || ' * 10^12 + ' || KEY_PART_2)                 AS NEW_PK_COLUMN_EXPRESSION
    FROM MS_RAW.STG_META.V_PRIMARY_KEYS
    WHERE PK_COLUMNS = 2
      AND SF_TABLE_NAME != 'PRICEBOOK_ENTRY'
    GROUP BY ALL
    ORDER BY ALL
    ;
    SELECT * FROM MS_RAW.STG_META.V_PRIMARY_KEYS_TWO ORDER BY ALL;