-- 3351
CREATE OR REPLACE TABLE MS_RAW.STG_META.SF_COLUMNS AS
SELECT
    -- MS
    SF_TABLES.MS_TABLE_SCHEMA,
    SF_TABLES.MS_TABLE_NAME,
    MS_INFO_COLUMNS.COLUMN_NAME AS MS_COLUMN_NAME,
    -- SF
    SF_TABLES.TABLE_SCHEMA,
    SF_TABLES.TABLE_NAME,
    SF_TABLES.NEW_TABLE_NAME,
    
    SF_INFO_COLUMNS.COLUMN_NAME,
    SF_INFO_COLUMNS.DATA_TYPE,
    SF_INFO_COLUMNS.CHARACTER_MAXIMUM_LENGTH,
    SF_INFO_COLUMNS.NUMERIC_PRECISION,
    SF_INFO_COLUMNS.NUMERIC_SCALE,
    SF_INFO_COLUMNS.DATETIME_PRECISION,

    -- NEW
    NULL::STRING           AS BASE_COLUMN_NAME,
    NULL::STRING           AS NEW_COLUMN_NAME,
    NULL::STRING           AS NEW_COLUMN_TYPE,
    NULL::STRING           AS NEW_COLUMN_EXPRESSION,

FROM ROL_RAW.INFORMATION_SCHEMA.COLUMNS AS SF_INFO_COLUMNS
INNER JOIN MS_RAW.STG_META.SF_TABLES AS SF_TABLES
    ON SF_INFO_COLUMNS.TABLE_SCHEMA = SF_TABLES.TABLE_SCHEMA
   AND SF_INFO_COLUMNS.TABLE_NAME   = SF_TABLES.TABLE_NAME
INNER JOIN ROL_RAW.REEDONLINE_META.COLUMNS AS MS_INFO_COLUMNS
    ON MS_INFO_COLUMNS.TABLE_SCHEMA = SF_TABLES.MS_TABLE_SCHEMA
   AND MS_INFO_COLUMNS.TABLE_NAME   = SF_TABLES.MS_TABLE_NAME
   AND UPPER(REPLACE(MS_INFO_COLUMNS.COLUMN_NAME, '_', '')) 
           = REPLACE(SF_INFO_COLUMNS.COLUMN_NAME, '_', '')
;
-- 3352
SELECT COUNT(*) FROM MS_RAW.STG_META.SF_COLUMNS;

-- 3352
UPDATE MS_RAW.STG_META.SF_COLUMNS
   SET NEW_COLUMN_NAME = REPLACE(REPLACE(REPLACE(
                         REPLACE(REPLACE(
                          '^' || COLUMN_NAME || '$'
                         ,'ECRUITER','RECRUITER')
                         ,'RRECRUITER','RECRUITER')
                         ,'DATE_OF_BIRTH','BIRTH_DATE')
                         ,'^','') 
                         ,'$','') 
;

-- 15
SELECT COLUMN_NAME, NEW_COLUMN_NAME
FROM MS_RAW.STG_META.SF_COLUMNS
WHERE COLUMN_NAME ILIKE ANY ('%ECRUITER%','DATE_OF_BIRTH') ESCAPE '\\'
GROUP BY ALL
ORDER BY ALL
;