---------------- BASE_COLUMN_NAME --------------------
UPDATE MS_RAW.STG_META.SF_COLUMNS
   SET BASE_COLUMN_NAME =
       REPLACE(REPLACE(REPLACE(REPLACE(
               REPLACE(REPLACE(
            '^_'|| NEW_COLUMN_NAME ||'_$'
            ,'_DATE_','_')
            ,'_RANGE_$','')
            ,'_ON_$','')
            ,'_AT_$','')
            ,'^_','')
            ,'_$','')
WHERE DATA_TYPE IN ('DATE','TIMESTAMP_TZ')
;

SELECT BASE_COLUMN_NAME, NEW_COLUMN_NAME, TABLE_NAME
FROM MS_RAW.STG_META.SF_COLUMNS
WHERE BASE_COLUMN_NAME IS NOT NULL
ORDER BY ALL
;

-------------- NEW_COLUMN_TYPE -------------------------
-- NEW_COLUMN_TYPE TIMESTAMP_TZ
UPDATE MS_RAW.STG_META.SF_COLUMNS
   SET NEW_COLUMN_TYPE = 'TIMESTAMP_NTZ' 
WHERE DATA_TYPE = 'TIMESTAMP_TZ'
;
-- NEW_COLUMN_TYPE DATE
UPDATE MS_RAW.STG_META.SF_COLUMNS
   SET NEW_COLUMN_TYPE = 'DATE'
WHERE           (TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME) 
      IN (SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME 
          FROM MS_RAW.STG_META.timestamp_column_analysis 
          WHERE is_date_only
         )
;
-- NEW_COLUMN_TYPE DATE
UPDATE MS_RAW.STG_META.SF_COLUMNS
   SET NEW_COLUMN_TYPE = 'DATE'
WHERE COLUMN_NAME LIKE '%BIRTH%'
;


--------------- NEW_COLUMN_NAME -----------------
-- NEW_COLUMN_NAME DATE
UPDATE MS_RAW.STG_META.SF_COLUMNS
   SET NEW_COLUMN_NAME = BASE_COLUMN_NAME || '_DATE'
WHERE DATA_TYPE = 'DATE' 
   OR NEW_COLUMN_TYPE = 'DATE'
;
-- NEW_COLUMN_NAME TIMESTAMP_NTZ
UPDATE MS_RAW.STG_META.SF_COLUMNS
   SET NEW_COLUMN_NAME = CASE WHEN ENDSWITH(BASE_COLUMN_NAME,'_FROM') 
                                OR ENDSWITH(BASE_COLUMN_NAME,'_UNTIL')
                                OR ENDSWITH(BASE_COLUMN_NAME,'_TO')
                              THEN BASE_COLUMN_NAME
                              ELSE BASE_COLUMN_NAME || '_AT'
                         END
WHERE NEW_COLUMN_TYPE = 'TIMESTAMP_NTZ'
;


------------------ NEW DATE COLUMN FOR EVERY TIMESTAMP_NTZ ------------
INSERT INTO MS_RAW.STG_META.SF_COLUMNS
      (TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, BASE_COLUMN_NAME, NEW_COLUMN_NAME,             NEW_COLUMN_TYPE, DATA_TYPE)  
SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, BASE_COLUMN_NAME, BASE_COLUMN_NAME || '_DATE', 'DATE',          DATA_TYPE  
FROM MS_RAW.STG_META.SF_COLUMNS
WHERE DATA_TYPE = 'TIMESTAMP_TZ'
  AND NEW_COLUMN_TYPE = 'TIMESTAMP_NTZ'
ORDER BY BASE_COLUMN_NAME
;

-- Check for duplicate names
SELECT TABLE_SCHEMA, TABLE_NAME, COALESCE(NEW_COLUMN_NAME, COLUMN_NAME) AS COLUMN_NAME
FROM MS_RAW.STG_META.SF_COLUMNS
GROUP BY ALL
HAVING COUNT(*) > 1
ORDER BY ALL;