UPDATE MS_RAW.STG_META.SF_COLUMNS
   SET NEW_COLUMN_TYPE = CASE WHEN DATA_TYPE = 'TIMESTAMP_TZ' THEN 'TIMESTAMP_NTZ' 
                              ELSE DATA_TYPE
                         END,
       BASE_COLUMN_NAME =
       REPLACE(REPLACE(REPLACE(REPLACE(
               REPLACE(REPLACE(
            '^_'||NEW_COLUMN_NAME||'_$'
            ,'_DATE_','_')
            ,'_RANGE_$','')
            ,'_ON_$','')
            ,'_AT_$','')
            ,'^_','')
            ,'_$','')
WHERE DATA_TYPE IN ('DATE','TIMESTAMP_TZ')
;

UPDATE MS_RAW.DBT_META.NEW_DATETIME_COLUMNS
   SET NEW_DATA_TYPE = 'DATE'
WHERE column_key IN (SELECT column_key FROM MS_RAW.DBT_META.timestamp_column_analysis WHERE is_date_only)
;

SELECT BASE_COLUMN_NAME, NEW_COLUMN_NAME, SF_TABLE_NAME
FROM MS_RAW.STG_META.SF_COLUMNS
WHERE BASE_COLUMN_NAME IS NOT NULL
ORDER BY ALL
;

UPDATE MS_RAW.STG_META.SF_COLUMNS
   SET NEW_COLUMN_NAME = BASE_COLUMN_NAME || '_DATE'
WHERE DATA_TYPE = 'DATE' 
   OR NEW_COLUMN_TYPE = 'DATE'
;
UPDATE MS_RAW.STG_META.SF_COLUMNS
   SET NEW_COLUMN_NAME = CASE WHEN ENDSWITH(BASE_COLUMN_NAME,'_FROM') 
                                OR ENDSWITH(BASE_COLUMN_NAME,'_UNTIL')
                                OR ENDSWITH(BASE_COLUMN_NAME,'_TO')
                              THEN BASE_COLUMN_NAME
                              ELSE BASE_COLUMN_NAME || '_AT'
                         END
WHERE NEW_COLUMN_TYPE = 'TIMESTAMP_NTZ'
;
INSERT INTO MS_RAW.STG_META.SF_COLUMNS
      (SF_TABLE_SCHEMA, SF_TABLE_NAME, SF_COLUMN_NAME, BASE_COLUMN_NAME, NEW_COLUMN_NAME,             NEW_COLUMN_TYPE, DATA_TYPE)  
SELECT SF_TABLE_SCHEMA, SF_TABLE_NAME, SF_COLUMN_NAME, BASE_COLUMN_NAME, BASE_COLUMN_NAME || '_DATE', 'DATE',          DATA_TYPE  
FROM MS_RAW.STG_META.SF_COLUMNS
WHERE DATA_TYPE = 'TIMESTAMP_TZ'
  AND NEW_COLUMN_TYPE = 'TIMESTAMP_NTZ'
  AND (SF_TABLE_SCHEMA, SF_TABLE_NAME, SF_COLUMN_NAME) NOT IN (SELECT SF_TABLE_SCHEMA, SF_TABLE_NAME, SF_COLUMN_NAME
                                                                FROM MS_RAW.STG_META.SF_COLUMNS
                                                               WHERE DATA_TYPE = 'TIMESTAMP_TZ'
                                                                 AND NEW_COLUMN_TYPE = 'DATE')
ORDER BY BASE_COLUMN_NAME
;