-- 300
INSERT INTO MS_RAW.STG_META.SF_COLUMNS
      (TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, BASE_COLUMN_NAME, NEW_COLUMN_NAME,    NEW_COLUMN_TYPE, DATA_TYPE) 
SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, '_DLT_LOAD_ID',   '_DLT_LOAD_ID_NUM', 'NUMBER(18,7)' , 'TEXT'
FROM ROL_RAW.INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = '_DLT_LOAD_ID'
  AND (TABLE_SCHEMA, TABLE_NAME) IN (SELECT TABLE_SCHEMA, TABLE_NAME 
                                       FROM MS_RAW.STG_META.SF_TABLES) 
  AND (TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME) NOT IN (SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME
                                                        FROM MS_RAW.STG_META.SF_COLUMNS
                                                       WHERE NEW_COLUMN_NAME = '_DLT_LOAD_ID_NUM')
;

-- 300
INSERT INTO MS_RAW.STG_META.SF_COLUMNS
      (TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, BASE_COLUMN_NAME, NEW_COLUMN_NAME,   NEW_COLUMN_TYPE,                   DATA_TYPE) 
SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, '_DLT_LOAD_ID',   '_DLT_LOAD_ID_AT', 'NUMBER(18,7)::TIMESTAMP_NTZ(9)' , 'TEXT'
FROM ROL_RAW.INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = '_DLT_LOAD_ID'
  AND (TABLE_SCHEMA, TABLE_NAME) IN (SELECT TABLE_SCHEMA, TABLE_NAME 
                                       FROM MS_RAW.STG_META.SF_TABLES) 
  AND (TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME) NOT IN (SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME
                                                        FROM MS_RAW.STG_META.SF_COLUMNS
                                                       WHERE NEW_COLUMN_NAME = '_DLT_LOAD_ID_AT')
;


SELECT * FROM MS_RAW.STG_META.SF_COLUMNS
WHERE COLUMN_NAME = '_DLT_LOAD_ID'
ORDER BY ALL
;

select _dlt_load_id::NUMBER(18,7)                   as _dlt_load_id_num, 
       _dlt_load_id::NUMBER(18,7)::timestamp_ntz(9) as _dlt_loaded_at,
       _dlt_load_id_num::timestamp_ntz(9)           as _dlt_loaded_at
from rol_raw.reedonline_dbo.users
limit 1;