-- 300
INSERT INTO MS_RAW.STG_META.SF_COLUMNS
      (  TABLE_SCHEMA,   TABLE_NAME,   COLUMN_NAME,   NEW_TABLE_NAME, BASE_COLUMN_NAME, NEW_COLUMN_NAME, NEW_COLUMN_TYPE,   DATA_TYPE) 
SELECT C.TABLE_SCHEMA, C.TABLE_NAME, C.COLUMN_NAME, T.NEW_TABLE_NAME, '_DLT_LOAD_ID',   '_DLT_LOAD_ID',  C.DATA_TYPE,     C.DATA_TYPE
FROM ROL_RAW.INFORMATION_SCHEMA.COLUMNS C
INNER JOIN MS_RAW.STG_META.SF_TABLES T
    ON C.TABLE_SCHEMA = T.TABLE_SCHEMA
   AND C.TABLE_NAME   = T.TABLE_NAME
WHERE COLUMN_NAME = '_DLT_LOAD_ID'
  AND NOT EXISTS (SELECT 1 FROM MS_RAW.STG_META.SF_COLUMNS S
                   WHERE S.TABLE_SCHEMA = C.TABLE_SCHEMA
                     AND S.TABLE_NAME   = C.TABLE_NAME
                     AND S.NEW_COLUMN_NAME = '_DLT_LOAD_ID')
;

-- 300
INSERT INTO MS_RAW.STG_META.SF_COLUMNS
      (TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, NEW_TABLE_NAME, BASE_COLUMN_NAME, NEW_COLUMN_NAME,    NEW_COLUMN_TYPE, DATA_TYPE) 
SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, NEW_TABLE_NAME, BASE_COLUMN_NAME, '_DLT_LOAD_ID_NUM', 'NUMBER(18,7)' , 'TEXT'
FROM MS_RAW.STG_META.SF_COLUMNS C
WHERE NEW_COLUMN_NAME = '_DLT_LOAD_ID'
  AND NOT EXISTS (SELECT 1 FROM MS_RAW.STG_META.SF_COLUMNS S
                   WHERE S.TABLE_SCHEMA = C.TABLE_SCHEMA
                     AND S.TABLE_NAME   = C.TABLE_NAME
                     AND S.NEW_COLUMN_NAME = '_DLT_LOAD_ID_NUM')
;

-- 300
INSERT INTO MS_RAW.STG_META.SF_COLUMNS
      (TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, NEW_TABLE_NAME, BASE_COLUMN_NAME, NEW_COLUMN_NAME,   NEW_COLUMN_TYPE,                   DATA_TYPE) 
SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, NEW_TABLE_NAME, BASE_COLUMN_NAME, '_DLT_LOAD_ID_AT', 'NUMBER(18,7)::TIMESTAMP_NTZ(9)' , 'TEXT'
FROM MS_RAW.STG_META.SF_COLUMNS C
WHERE NEW_COLUMN_NAME = '_DLT_LOAD_ID'
  AND NOT EXISTS (SELECT 1 FROM MS_RAW.STG_META.SF_COLUMNS S
                   WHERE S.TABLE_SCHEMA = C.TABLE_SCHEMA
                     AND S.TABLE_NAME   = C.TABLE_NAME
                     AND S.NEW_COLUMN_NAME = '_DLT_LOAD_ID_AT')
;

-- 900
SELECT * FROM MS_RAW.STG_META.SF_COLUMNS
WHERE COLUMN_NAME = '_DLT_LOAD_ID'
ORDER BY ALL
;

/*
select _dlt_load_id::NUMBER(18,7)                   as _dlt_load_id_num, 
       _dlt_load_id::NUMBER(18,7)::timestamp_ntz(9) as _dlt_loaded_at,
       _dlt_load_id_num::timestamp_ntz(9)           as _dlt_loaded_at
from rol_raw.reedonline_dbo.users
limit 1;
*/