-- for _BW ADD NEW COLUMN REPLACING _BW with _ID

-- TABLES ('USER_CONTACT_PREF_BW','USER_ACCOUNT_BW') ALREAD
-- EXCLUDING TABLES THAT CONTAIN SF_COLUMN_NAME IN ('USER_CONTACT_PREF_BW','USER_ACCOUNT_BW')
-- THIS COLUMNS WILL BE ADDED FROM PK.SQL FOR KEYS WITH 2 COLUMNS

/*
DELETE --  SELECT *
FROM MS_RAW.STG_META.SF_COLUMNS
WHERE COLUMN_NAME ILIKE '%_BW'
  AND NEW_COLUMN_NAME ILIKE '%_ID'
-- ORDER BY ALL
;
*/

INSERT INTO MS_RAW.STG_META.SF_COLUMNS
      (TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, NEW_TABLE_NAME,
       BASE_COLUMN_NAME,
       NEW_COLUMN_NAME, 
       DATA_TYPE,
       NEW_COLUMN_EXPRESSION)
SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, NEW_TABLE_NAME,
       REPLACE(COLUMN_NAME,'_BW','') AS BASE_COLUMN_NAME,
       CASE WHEN NEW_TABLE_NAME = 'USER_ACCOUNT_ACTION' --??????????? FK TABLE NAME HAS TO BE INCLUDED!!!
            THEN 'USER_ACCOUNT_ACTION_ID'
            ELSE REPLACE(COLUMN_NAME,'_BW','_ID') 
       END AS NEW_COLUMN_NAME, 
       DATA_TYPE,
       CASE WHEN (NEW_TABLE_NAME = 'USER_CONTACT_PREF' AND NEW_COLUMN_NAME = 'USER_CONTACT_PREF_BW')
            THEN 'USER_TYPE_ID * POWER(10, 12) + USER_CONTACT_PREF_BW'
            WHEN (NEW_TABLE_NAME = 'USER_ACCOUNT'      AND NEW_COLUMN_NAME = 'USER_ACCOUNT_BW')
            THEN 'USER_TYPE_ID * POWER(10, 12) + USER_ACCOUNT_BW'
            ELSE NEW_COLUMN_EXPRESSION
       END 
FROM MS_RAW.STG_META.SF_COLUMNS AS C
WHERE COLUMN_NAME ILIKE '%_BW'
  AND NOT COALESCE(NEW_COLUMN_NAME,'') = REPLACE(COLUMN_NAME,'_BW','_ID')
  AND NOT EXISTS (SELECT 1 FROM MS_RAW.STG_META.SF_COLUMNS AS S
                  WHERE S.TABLE_SCHEMA = C.TABLE_SCHEMA
                    AND S.TABLE_NAME   = C.TABLE_NAME
                    AND S.COLUMN_NAME  = C.COLUMN_NAME
                    AND S.NEW_COLUMN_NAME ILIKE '%_ID')  
ORDER BY TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, BASE_COLUMN_NAME, NEW_COLUMN_NAME
;

-- 0
SELECT * -- TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, BASE_COLUMN_NAME, NEW_COLUMN_NAME
FROM MS_RAW.STG_META.SF_COLUMNS
GROUP BY ALL
HAVING COUNT(*) > 1
ORDER BY ALL;

-- 36, 18, 18
SELECT * 
FROM MS_RAW.STG_META.SF_COLUMNS
 WHERE COLUMN_NAME ILIKE '%_BW'
--   AND NEW_COLUMN_NAME IS NULL
--   AND NEW_COLUMN_NAME = REPLACE(COLUMN_NAME,'_BW','_ID')
ORDER BY TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, BASE_COLUMN_NAME, NEW_COLUMN_NAME
;

