-- for _BW ADD NEW COLUMN REPLACING _BW with _ID

-- TABLES ('USER_CONTACT_PREF_BW','USER_ACCOUNT_BW') ALREAD
-- EXCLUDING TABLES THAT CONTAIN SF_COLUMN_NAME IN ('USER_CONTACT_PREF_BW','USER_ACCOUNT_BW')
-- THIS COLUMNS WILL BE ADDED FROM PK.SQL FOR KEYS WITH 2 COLUMNS

-- 15                    
INSERT INTO MS_RAW.STG_META.SF_COLUMNS
      (TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, 
       BASE_COLUMN_NAME,
       NEW_COLUMN_NAME, 
       DATA_TYPE)
SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, 
       REPLACE(COLUMN_NAME,'_BW','') AS BASE_COLUMN_NAME,
       REPLACE(COLUMN_NAME,'_BW','_ID') AS NEW_COLUMN_NAME, 
       DATA_TYPE
FROM MS_RAW.STG_META.SF_COLUMNS AS C
WHERE COLUMN_NAME ILIKE '%_BW'
  AND TABLE_NAME NOT IN ('USER_CONTACT_PREF_FACT','USER_ACCOUNT_FACT','USER_ACCOUNT_ACTION') -- PK WITH 2 COLUMNS
  AND NOT EXISTS (SELECT 1 FROM MS_RAW.STG_META.SF_COLUMNS AS S
                  WHERE S.TABLE_SCHEMA = C.TABLE_SCHEMA
                    AND S.TABLE_NAME   = C.TABLE_NAME
                    AND S.COLUMN_NAME  = C.COLUMN_NAME
                    AND S.NEW_COLUMN_NAME ILIKE '%_ID')  
--ORDER BY TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, BASE_COLUMN_NAME, NEW_COLUMN_NAME
;

-- 0
SELECT * -- TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, BASE_COLUMN_NAME, NEW_COLUMN_NAME
FROM MS_RAW.STG_META.SF_COLUMNS
GROUP BY ALL
HAVING COUNT(*) > 1
ORDER BY ALL;

-- 33, 18, 15
SELECT * 
FROM MS_RAW.STG_META.SF_COLUMNS
 WHERE COLUMN_NAME ILIKE '%_BW'
--   AND NEW_COLUMN_NAME = COLUMN_NAME        -- 18
--   AND NEW_COLUMN_NAME = REPLACE(COLUMN_NAME,'_BW','_ID')   -- 15
ORDER BY TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, BASE_COLUMN_NAME, NEW_COLUMN_NAME
;

