-- for _BW ADD NEW COLUMN REPLACING _BW with _ID
-- EXCLUDING NEW TABLE NAME 'USER_CONTACT_PREF' (IT HAS KEY WITH 2 COLUMN)
-- THE NEW _ID WILL BE FK IF NEW_TABLE_NAME <> PREFIX OR PK IF = PREFIX
-- for table USER_CONTACT_PREF the new key will be defined from the SURROGATE KEY




CREATE OR REPLACE TRANSIENT TABLE MS_RAW.STG_META.T_PRIMARY_KEYS AS
    SELECT
        sfc.TABLE_SCHEMA,
        sfc.TABLE_NAME,
        sfc.COLUMN_NAME,
        sfc.MS_TABLE_SCHEMA,
        sfc.MS_TABLE_NAME,
        sfc.MS_COLUMN_NAME,
        sft.NEW_TABLE_NAME,
        sft.NEW_TABLE_NAME || '_ID' AS NEW_TABLE_NAME_ID,
        CASE WHEN sfc.COLUMN_NAME ILIKE '%_BW'
             THEN NEW_TABLE_NAME_ID
             ELSE sfc.NEW_COLUMN_NAME
        END AS NEW_COLUMN_NAME,
        kcu.CONSTRAINT_SCHEMA,
        kcu.CONSTRAINT_NAME,
        kcu.TABLE_NAME AS CONSTRAINT_TABLE_NAME,
        FIRST_VALUE(sfc.COLUMN_NAME)  
            OVER (PARTITION BY sfc.TABLE_SCHEMA, sfc.TABLE_NAME ORDER BY kcu.ORDINAL_POSITION) 
                                           AS KEY_PART_1,
        LAST_VALUE(sfc.COLUMN_NAME)  
            OVER (PARTITION BY sfc.TABLE_SCHEMA, sfc.TABLE_NAME ORDER BY kcu.ORDINAL_POSITION) 
                                           AS KEY_PART_2,
        LISTAGG(sfc.COLUMN_NAME,',') 
            OVER (PARTITION BY kcu.CONSTRAINT_SCHEMA, kcu.CONSTRAINT_NAME) AS PK_COLUMN_NAMES,
        COUNT(*) 
            OVER (PARTITION BY kcu.CONSTRAINT_SCHEMA, kcu.CONSTRAINT_NAME) AS PK_COLUMNS,
        COUNT(DISTINCT kcu.CONSTRAINT_SCHEMA, kcu.CONSTRAINT_NAME) 
            OVER (PARTITION BY sfc.TABLE_SCHEMA, sfc.COLUMN_NAME) AS PK_TABLES,
        kcu.ORDINAL_POSITION
    FROM ROL_RAW.REEDONLINE_META.TABLE_CONSTRAINTS tc
    INNER JOIN ROL_RAW.REEDONLINE_META.KEY_COLUMN_USAGE kcu
        ON  kcu.TABLE_SCHEMA    = tc.TABLE_SCHEMA
        AND kcu.TABLE_NAME      = tc.TABLE_NAME
        AND kcu.CONSTRAINT_NAME = tc.CONSTRAINT_NAME
    INNER JOIN MS_RAW.STG_META.SF_COLUMNS sfc
        ON  kcu.TABLE_SCHEMA = sfc.MS_TABLE_SCHEMA
        AND kcu.TABLE_NAME   = sfc.MS_TABLE_NAME
        AND kcu.COLUMN_NAME  = sfc.MS_COLUMN_NAME
    INNER JOIN MS_RAW.STG_META.SF_TABLES sft
        ON sfc.TABLE_SCHEMA = sft.TABLE_SCHEMA
       AND sfc.TABLE_NAME   = sft.TABLE_NAME
    WHERE tc.CONSTRAINT_TYPE = 'PRIMARY KEY'
      AND sfc.TABLE_NAME != 'PRICEBOOK_ENTRY' -- pk has 5 columns
     ORDER BY ALL;

    SELECT *
    FROM MS_RAW.STG_META.T_PRIMARY_KEYS
    ORDER BY ALL;

    -- CHECK FOR TABLES WITHOUT PRIMARY KEY COLUMN
    SELECT T.* 
    FROM MS_RAW.STG_META.T_PRIMARY_KEYS AS T
    LEFT JOIN MS_RAW.STG_META.SF_COLUMNS AS C
      ON T.TABLE_NAME = C.TABLE_NAME
     AND T.TABLE_SCHEMA = C.TABLE_SCHEMA
     AND T.NEW_COLUMN_NAME = C.NEW_COLUMN_NAME
    WHERE C.COLUMN_NAME IS NULL
    ORDER BY ALL
    ;

    -- 299 TABLES, 277 ONE_PK_COLUMN, 22 TWO_PK_COLUMNS
    SELECT COUNT(DISTINCT TABLE_SCHEMA, TABLE_NAME) AS TOTAL_TABLES
         , COUNT_IF(PK_COLUMNS = 1) as ONE_PK_COLUMN
         , COUNT_IF(PK_COLUMNS = 2) / 2 as TWO_PK_COLUMNS
         , count(*) AS TOTAL_COLUMNS
    FROM MS_RAW.STG_META.T_PRIMARY_KEYS;


    -- 299
    UPDATE MS_RAW.STG_META.SF_TABLES AS t
       SET PRIMARY_KEY_NAME     = CASE WHEN pk.PK_COLUMNS = 1
                                       THEN pk.COLUMN_NAME
                                       ELSE pk.NEW_TABLE_NAME_ID
                                  END,
           PK_COLUMNS           = pk.PK_COLUMNS,
           PK_TABLES            = pk.PK_TABLES,
           NEW_PRIMARY_KEY_NAME = pk.NEW_TABLE_NAME_ID,
           NEW_PRIMARY_KEY_EXPRESSION =
                CASE WHEN pk.PK_COLUMNS = 2
                     THEN pk.KEY_PART_2 || ' * POWER(10, 12) + ' || pk.KEY_PART_1
                     ELSE NULL
                END,
           NEW_PRIMARY_KEY_UNIQUE_COLUMNS =
                CASE WHEN pk.PK_COLUMNS = 2
                     THEN pk.KEY_PART_2 || ',' || pk.KEY_PART_1
                     ELSE NULL
                END
       FROM MS_RAW.STG_META.T_PRIMARY_KEYS AS pk
      WHERE pk.table_schema = t.table_schema
        AND pk.table_name   = t.table_name
        AND pk.ORDINAL_POSITION = 1
    ;
    
------------------------- PK_COLUMNS = 2 <START> ----------------------------------

    CREATE OR REPLACE TRANSIENT TABLE MS_RAW.STG_META.T_PRIMARY_KEYS_TWO_DBT_UNIQUE AS
    SELECT sfc.TABLE_SCHEMA, 
           sfc.TABLE_NAME, 
           sfc.COLUMN_NAME,
           pk.ORDINAL_POSITION
    FROM MS_RAW.STG_META.T_PRIMARY_KEYS pk
    INNER JOIN MS_RAW.STG_META.SF_COLUMNS sfc
        ON  pk.TABLE_SCHEMA = sfc.TABLE_SCHEMA
        AND pk.TABLE_NAME   = sfc.TABLE_NAME
        AND pk.COLUMN_NAME  = sfc.COLUMN_NAME
    INNER JOIN MS_RAW.STG_META.SF_TABLES sft
        ON  sft.TABLE_SCHEMA = sfc.TABLE_SCHEMA
        AND sft.TABLE_NAME   = sfc.TABLE_NAME
    WHERE pk.PK_COLUMNS = 2
    ORDER BY ALL
    ;

    CREATE OR REPLACE VIEW MS_RAW.STG_META.T_PRIMARY_KEYS_TWO AS
    WITH TWO_COLUMNS AS (
        SELECT TABLE_SCHEMA, 
               TABLE_NAME, 
               FIRST_VALUE(COLUMN_NAME)  
                    OVER (PARTITION BY TABLE_SCHEMA, TABLE_NAME ORDER BY ORDINAL_POSITION) 
                                                                 AS KEY_PART_1,
               LAST_VALUE(COLUMN_NAME)  
                    OVER (PARTITION BY TABLE_SCHEMA, TABLE_NAME ORDER BY ORDINAL_POSITION) 
                                                                 AS KEY_PART_2,
               CASE WHEN TABLE_NAME IN ('USER_CONTACT_PREF_FACT','USER_ACCOUNT_ACTION')
                    THEN KEY_PART_2 || ' * POWER(10, 12) + ' || KEY_PART_1
                    ELSE KEY_PART_1 || ' * POWER(10, 12) + ' || KEY_PART_2
               END                        AS NEW_PRIMARY_KEY_EXPRESSION,
               CASE WHEN TABLE_NAME IN ('USER_CONTACT_PREF_FACT','USER_ACCOUNT_ACTION')
                    THEN KEY_PART_2 || ',' || KEY_PART_1
                    ELSE KEY_PART_1 || ',' || KEY_PART_2
               END                        AS NEW_PRIMARY_KEY_UNIQUE_COLUMNS,
               
        FROM MS_RAW.STG_META.T_PRIMARY_KEYS_TWO_DBT_UNIQUE 
    )
    SELECT TABLE_SCHEMA, 
           TABLE_NAME, 
           NEW_PRIMARY_KEY_EXPRESSION,
           NEW_PRIMARY_KEY_UNIQUE_COLUMNS
    FROM TWO_COLUMNS
    GROUP BY ALL
    ORDER BY ALL
    ;

    -- 22
    SELECT * FROM MS_RAW.STG_META.V_PRIMARY_KEYS_TWO 
    ORDER BY ALL;

    -- 22
    UPDATE MS_RAW.STG_META.SF_TABLES AS t
       SET PRIMARY_KEY_NAME     = NEW_TABLE_NAME || '_ID',
           PK_COLUMNS           = 2,
           PK_TABLES            = 1,
           NEW_PRIMARY_KEY_NAME = NEW_TABLE_NAME || '_ID',
           NEW_PRIMARY_KEY_EXPRESSION = pk2.NEW_PRIMARY_KEY_EXPRESSION,
           NEW_PRIMARY_KEY_UNIQUE_COLUMNS = pk2.NEW_PRIMARY_KEY_UNIQUE_COLUMNS
      FROM MS_RAW.STG_META.V_PRIMARY_KEYS_TWO AS pk2
      WHERE t.table_schema = pk2.table_schema
        AND t.table_name   = pk2.table_name
    ;

    -- Special Case
    UPDATE MS_RAW.STG_META.SF_TABLES
       SET PK_COLUMNS           = 1,
           NEW_PRIMARY_KEY_EXPRESSION = NULL
     WHERE TABLE_NAME   = 'RATE_CARD_TIER'
    ;

    -- 21 (22 - 1)
    SELECT * FROM MS_RAW.STG_META.SF_TABLES
    WHERE PK_COLUMNS = 2
      AND NEW_PRIMARY_KEY_EXPRESSION IS NOT NULL
    ORDER BY ALL
    ;

    INSERT INTO MS_RAW.STG_META.SF_COLUMNS
      (TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, 
       BASE_COLUMN_NAME,
       NEW_COLUMN_NAME, 
       DATA_TYPE,
       NEW_COLUMN_EXPRESSION)
SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, 
       REPLACE(COLUMN_NAME,'_BW','') AS BASE_COLUMN_NAME,
       CASE WHEN TABLE_NAME = 'USER_ACCOUNT_ACTION' --??????????? FK TABLE NAME HAS TO BE INCLUDED!!!
            THEN 'USER_ACCOUNT_ACTION_ID'
            ELSE REPLACE(COLUMN_NAME,'_BW','_ID') 
       END AS NEW_COLUMN_NAME, 
       DATA_TYPE,
       CASE WHEN (TABLE_NAME = 'USER_CONTACT_PREF' AND NEW_COLUMN_NAME = 'USER_CONTACT_PREF_BW')
            THEN 'USER_TYPE_ID * POWER(10, 12) + USER_CONTACT_PREF_BW'
            WHEN (TABLE_NAME = 'USER_ACCOUNT'      AND NEW_COLUMN_NAME = 'USER_ACCOUNT_BW')
            THEN 'USER_TYPE_ID * POWER(10, 12) + USER_ACCOUNT_BW'
            ELSE NEW_COLUMN_EXPRESSION
       END 
FROM MS_RAW.STG_META.SF_COLUMNS AS C
WHERE COLUMN_NAME ILIKE '%_BW'
  AND NOT COALESCE(NEW_COLUMN_NAME,'') = REPLACE(COLUMN_NAME,'_BW','_ID')
  AND NOT EXISTS (SELECT 1 FROM MS_RAW.STG_META.SF_COLUMNS AS S
                  WHERE S.TABLE_SCHEMA = C.TABLE_SCHEMA
                    AND S.TABLE_NAME   = C.TABLE_NAME
                    AND S.COLUMN_NAME  = C.COLUMN_NAME
                    AND S.NEW_COLUMN_NAME ILIKE '%_ID')  
ORDER BY TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, BASE_COLUMN_NAME, NEW_COLUMN_NAME
;
------------------------- PK_COLUMNS = 2 <END> ----------------------------------
   
  ----------- PK_COLUMNS = 1  AND NEW_TABLE_NAME_ID = NEW_COLUMN_NAME <START> ----------------

    CREATE OR REPLACE VIEW MS_RAW.STG_META.V_PRIMARY_KEYS_TABLE_ID AS
    SELECT TABLE_SCHEMA, 
           TABLE_NAME, 
           COLUMN_NAME, 
           NEW_TABLE_NAME, 
           NEW_COLUMN_NAME,
           NEW_TABLE_NAME_ID,
           PK_TABLES,
    FROM MS_RAW.STG_META.T_PRIMARY_KEYS K
    WHERE PK_COLUMNS = 1
      AND NEW_TABLE_NAME_ID = NEW_COLUMN_NAME
    ORDER BY TABLE_SCHEMA, NEW_TABLE_NAME; 

    -- 219
    SELECT * FROM MS_RAW.STG_META.V_PRIMARY_KEYS_TABLE_ID ORDER BY ALL;

    -- 219
    UPDATE MS_RAW.STG_META.SF_TABLES AS t
       SET PRIMARY_KEY_NAME     = pk2.COLUMN_NAME,
           PK_COLUMNS           = 1,
           PK_TABLES            = pk2.PK_TABLES,
           NEW_PRIMARY_KEY_NAME = pk2.NEW_TABLE_NAME_ID
      FROM MS_RAW.STG_META.V_PRIMARY_KEYS_TABLE_ID AS pk2
      WHERE t.table_schema = pk2.table_schema
        AND t.table_name   = pk2.table_name
    ;

      -- 220 (219 + 1)
    SELECT * FROM MS_RAW.STG_META.SF_TABLES
    WHERE PK_COLUMNS = 1
      AND NEW_PRIMARY_KEY_NAME = NEW_TABLE_NAME || '_ID'
    ORDER BY ALL
    ;
    
    ----------- pk.PK_TABLES > 1
    -- 12
    CREATE OR REPLACE VIEW MS_RAW.STG_META.V_PRIMARY_KEYS_TABLE_ID_MANY AS;
    SELECT pk.TABLE_SCHEMA, 
           pk.TABLE_NAME, 
           pk.COLUMN_NAME, 
           pk.NEW_TABLE_NAME, 
           pk.NEW_COLUMN_NAME,
           pk.NEW_TABLE_NAME_ID,
           pk.PK_TABLES,
           t.TABLE_NAME as PK_TABLE_NAME,
           t.NEW_PRIMARY_KEY_NAME
    FROM MS_RAW.STG_META.T_PRIMARY_KEYS AS pk
    INNER JOIN MS_RAW.STG_META.SF_TABLES AS t
        ON t.TABLE_SCHEMA      = pk.TABLE_SCHEMA
       AND t.NEW_PRIMARY_KEY_NAME = pk.NEW_COLUMN_NAME
       AND t.NEW_PRIMARY_KEY_NAME = T.NEW_TABLE_NAME || '_ID'
    WHERE pk.NEW_TABLE_NAME_ID != pk.NEW_COLUMN_NAME
      AND pk.PK_TABLES > 1
      AND pk.TABLE_NAME != pk.NEW_TABLE_NAME
--      AND pk.TABLE_NAME NOT IN ('USER_CONTACT_PREF_FACT','USER_ACCOUNT_ACTION')
    GROUP BY ALL
    ORDER BY pk.TABLE_SCHEMA, pk.NEW_TABLE_NAME, pk.TABLE_NAME;

    -- 41, 30
    SELECT count(*), count(distinct table_schema, table_name)
      FROM MS_RAW.STG_META.V_PRIMARY_KEYS_TABLE_ID_MANY 
    ORDER BY NEW_COLUMN_NAME;

    -- 12
    UPDATE MS_RAW.STG_META.TABLES AS t
       SET PRIMARY_KEY_NAME     = COLUMN_NAME,
           PK_COLUMNS           = 1,
           PK_TABLES            = pk2.PK_TABLES,
           NEW_PRIMARY_KEY_NAME = NEW_COLUMN_NAME
      FROM MS_RAW.STG_META.V_PRIMARY_KEYS_TABLE_ID_MANY AS pk2
      WHERE t.table_schema = pk2.table_schema
        AND t.table_name   = pk2.table_name
    ;
  
    -- 12
    DELETE FROM MS_RAW.STG_META.T_PRIMARY_KEYS
    WHERE (table_schema, table_name)
       in (select table_schema, table_name from MS_RAW.STG_META.V_PRIMARY_KEYS_TABLE_ID_MANY)
    ;

  ----------- PK_COLUMNS = 1  AND NEW_TABLE_NAME_ID = NEW_COLUMN_NAME <END> ----------------
  ----------- PK_COLUMNS = 1  AND NEW_TABLE_NAME_ID != NEW_COLUMN_NAME <START> ----------------
    -- 46
    SELECT * FROM MS_RAW.STG_META.T_PRIMARY_KEYS 
    ORDER BY NEW_COLUMN_NAME;

    -- 40
    SELECT * FROM MS_RAW.STG_META.T_PRIMARY_KEYS 
    WHERE NEW_COLUMN_NAME != NEW_TABLE_NAME_ID
    ORDER BY NEW_COLUMN_NAME;

    -- 46
    UPDATE MS_RAW.STG_META.TABLES AS t
     SET PRIMARY_KEY_NAME     = pk2.COLUMN_NAME,
         PK_COLUMNS           = 1,
         PK_TABLES            = pk2.PK_TABLES,
         NEW_PRIMARY_KEY_NAME = pk2.NEW_TABLE_NAME_ID
    FROM MS_RAW.STG_META.T_PRIMARY_KEYS AS pk2
    WHERE t.table_schema = pk2.table_schema
      AND t.table_name   = pk2.table_name
    ;

    ----------- START  PK_COLUMNS = 1  AND NEW_TABLE_NAME_ID != NEW_COLUMN_NAME <END> ----------------

-- EMPTY   
SELECT *
FROM MS_RAW.STG_META.TABLES
WHERE TABLE_NAME != 'PRICEBOOK_ENTRY'
  AND PRIMARY_KEY_NAME IS NULL
ORDER BY ALL
;

-- STATS FROM PK IN TABLES
SELECT COUNT(*),                                                  --299
       COUNT(CASE WHEN PK_COLUMNS  = 1 THEN 1 END) AS ONE_COLUMN, --278
       COUNT(CASE WHEN PK_COLUMNS != 1 THEN 1 END) AS TWO_COLUMN, -- 21
       COUNT(CASE WHEN PRIMARY_KEY_NAME IS NULL THEN 1 END) AS NO_PRIMARY_KEY_NAME, -- 0
       COUNT(CASE WHEN (NEW_TABLE_NAME IS NULL OR NEW_PRIMARY_KEY_NAME IS NULL) THEN 1 END) AS NO_NEW, -- 0
       COUNT(CASE WHEN ENDSWITH(NEW_PRIMARY_KEY_NAME,'_ID')                     THEN 1 END) AS ENDSWITH_ID,              -- 299
       COUNT(CASE WHEN NEW_TABLE_NAME || '_ID'  = NEW_PRIMARY_KEY_NAME                     THEN 1 END) AS MASTER_PKS,    -- 287
       COUNT(CASE WHEN NEW_TABLE_NAME || '_ID'  = NEW_PRIMARY_KEY_NAME AND PK_COLUMNS != 1 THEN 1 END) AS MASTER_PKS2,   --  21
       COUNT(CASE WHEN NEW_TABLE_NAME || '_ID'  = NEW_PRIMARY_KEY_NAME AND PK_COLUMNS  = 1 THEN 1 END) AS MASTER_PKS1,   -- 266
       COUNT(CASE WHEN NEW_TABLE_NAME || '_ID' != NEW_PRIMARY_KEY_NAME                     THEN 1 END) AS SECONDARY_PKS1,--  12
FROM MS_RAW.STG_META.TABLES
WHERE TABLE_NAME != 'PRICEBOOK_ENTRY'
;

-- STATS FROM PK IN TABLES where sft.PK_COLUMNS = 1 
SELECT COUNT(*), -- 284
       COUNT(CASE WHEN ENDSWITH(sft.NEW_PRIMARY_KEY_NAME,'_ID')                                        THEN 1 END) AS ENDSWITH_ID,   -- 284
       COUNT(CASE WHEN sft.NEW_TABLE_NAME || '_ID'  = sft.NEW_PRIMARY_KEY_NAME                         THEN 1 END) AS MASTER_PKS,    -- 272
       COUNT(CASE WHEN sft.NEW_TABLE_NAME || '_ID' != sft.NEW_PRIMARY_KEY_NAME                         THEN 1 END) AS SECONDARY_PKS1,--  12
FROM MS_RAW.STG_META.TABLES sft
INNER JOIN MS_RAW.STG_META.COLUMNS sfc
   ON sft.TABLE_SCHEMA  = sfc.TABLE_SCHEMA
  AND sft.TABLE_NAME    = sfc.TABLE_NAME
  AND sft.PRIMARY_KEY_NAME = sfc.COLUMN_NAME
WHERE sft.TABLE_NAME != 'PRICEBOOK_ENTRY'
  AND sft.PK_COLUMNS = 1 
;

-- STATS FROM PK IN TABLES where sft.PK_COLUMNS = 2 
SELECT COUNT(*), -- 21
       COUNT(CASE WHEN sft.NEW_TABLE_NAME || '_ID'  = sft.NEW_PRIMARY_KEY_NAME                         THEN 1 END) AS MASTER_PKS,    -- 21
FROM MS_RAW.STG_META.TABLES sft
WHERE sft.PK_COLUMNS = 2 
;


-- INSERT THE NEW COLUMNS IN COLUMNS >>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- STATS FROM PK IN TABLES where sft.PK_COLUMNS = 2 
SELECT COUNT(*), -- 0
       COUNT(CASE WHEN sft.NEW_TABLE_NAME || '_ID'  = sft.NEW_PRIMARY_KEY_NAME                         THEN 1 END) AS MASTER_PKS,    -- 21
FROM MS_RAW.STG_META.TABLES sft
LEFT JOIN MS_RAW.STG_META.COLUMNS sfc
   ON sft.TABLE_SCHEMA  = sfc.TABLE_SCHEMA
  AND sft.TABLE_NAME    = sfc.TABLE_NAME
  AND sft.PRIMARY_KEY_NAME = sfc.COLUMN_NAME
WHERE sft.PK_COLUMNS = 2 
  AND sfc.COLUMN_NAME IS NULL
;

INSERT INTO MS_RAW.STG_META.COLUMNS
      (TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, 
       NEW_COLUMN_NAME, NEW_COLUMN_TYPE, NEW_COLUMN_EXPRESSION)
SELECT TABLE_SCHEMA, TABLE_NAME, NEW_PRIMARY_KEY_NAME, 
       NEW_PRIMARY_KEY_NAME, 'NUMERIC(18,0)', NEW_PRIMARY_KEY_EXPRESSION
FROM MS_RAW.STG_META.TABLES
WHERE PK_COLUMNS = 2
  AND (TABLE_SCHEMA, TABLE_NAME, NEW_PRIMARY_KEY_NAME)
      NOT IN (SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME
              FROM MS_RAW.STG_META.COLUMNS)
;
