-- for _BW ADD NEW COLUMN REPLACING _BW with _ID
-- EXCLUDING NEW TABLE NAME 'USER_CONTACT_PREF' (IT HAS KEY WITH 2 COLUMN)
-- THE NEW _ID WILL BE FK IF NEW_TABLE_NAME <> PREFIX OR PK IF = PREFIX
-- for table USER_CONTACT_PREF the new key will be defined from the SURROGATE KEY




CREATE OR REPLACE TRANSIENT TABLE MS_RAW.STG_META.T_PRIMARY_KEYS AS
SELECT
    tc.CONSTRAINT_NAME AS PK_CONSTRAINT_NAME,
    sfc.TABLE_SCHEMA,
    sfc.TABLE_NAME,
    sfc.COLUMN_NAME,
    sfc.MS_TABLE_SCHEMA,
    sfc.MS_TABLE_NAME,
    sfc.MS_COLUMN_NAME,
    sft.NEW_TABLE_NAME,
    sft.NEW_TABLE_NAME || '_ID' AS NEW_TABLE_NAME_ID,
    CASE WHEN sfc.COLUMN_NAME ILIKE '%_BW'
           OR sfc.COLUMN_NAME = 'ID'
         THEN NEW_TABLE_NAME_ID
         ELSE sfc.NEW_COLUMN_NAME
    END AS NEW_COLUMN_NAME,
    kcu.CONSTRAINT_SCHEMA,
    kcu.CONSTRAINT_NAME,
    kcu.TABLE_NAME AS CONSTRAINT_TABLE_NAME,
    FIRST_VALUE(sfc.COLUMN_NAME)  
        OVER (PARTITION BY sfc.TABLE_SCHEMA, sfc.TABLE_NAME ORDER BY kcu.ORDINAL_POSITION) 
                                       AS KEY_PART_1,
    LAST_VALUE(sfc.COLUMN_NAME)  
        OVER (PARTITION BY sfc.TABLE_SCHEMA, sfc.TABLE_NAME ORDER BY kcu.ORDINAL_POSITION) 
                                       AS KEY_PART_2,
    LISTAGG(sfc.COLUMN_NAME,',') 
        OVER (PARTITION BY kcu.CONSTRAINT_SCHEMA, kcu.CONSTRAINT_NAME) AS PK_COLUMN_NAMES,
    COUNT(*) 
        OVER (PARTITION BY kcu.CONSTRAINT_SCHEMA, kcu.CONSTRAINT_NAME) AS PK_COLUMNS,
    COUNT(DISTINCT kcu.CONSTRAINT_SCHEMA, kcu.CONSTRAINT_NAME) 
        OVER (PARTITION BY sfc.TABLE_SCHEMA, sfc.COLUMN_NAME) AS PK_TABLES,
    kcu.ORDINAL_POSITION,
    FALSE AS IS_MASTER_ID
FROM ROL_RAW.REEDONLINE_META.TABLE_CONSTRAINTS tc
INNER JOIN ROL_RAW.REEDONLINE_META.KEY_COLUMN_USAGE kcu
    ON  kcu.TABLE_SCHEMA    = tc.TABLE_SCHEMA
    AND kcu.TABLE_NAME      = tc.TABLE_NAME
    AND kcu.CONSTRAINT_NAME = tc.CONSTRAINT_NAME
INNER JOIN MS_RAW.STG_META.SF_COLUMNS sfc
    ON  kcu.TABLE_SCHEMA = sfc.MS_TABLE_SCHEMA
    AND kcu.TABLE_NAME   = sfc.MS_TABLE_NAME
    AND kcu.COLUMN_NAME  = sfc.MS_COLUMN_NAME
INNER JOIN MS_RAW.STG_META.SF_TABLES sft
    ON sfc.TABLE_SCHEMA = sft.TABLE_SCHEMA
   AND sfc.TABLE_NAME   = sft.TABLE_NAME
WHERE tc.CONSTRAINT_TYPE = 'PRIMARY KEY'
  AND sfc.TABLE_NAME != 'PRICEBOOK_ENTRY' -- pk has 5 columns
ORDER BY ALL
;

-- CHECK FOR TABLES WITHOUT PRIMARY KEY COLUMN
SELECT PK.* 
FROM MS_RAW.STG_META.T_PRIMARY_KEYS AS PK
LEFT JOIN MS_RAW.STG_META.SF_COLUMNS AS C
  ON PK.TABLE_NAME   = C.TABLE_NAME
 AND PK.TABLE_SCHEMA = C.TABLE_SCHEMA
 AND PK.COLUMN_NAME  = C.COLUMN_NAME
WHERE C.COLUMN_NAME IS NULL
ORDER BY ALL
;

-- 299 TABLES, 277 ONE_PK_COLUMN, 22 TWO_PK_COLUMNS, 321
SELECT COUNT(DISTINCT TABLE_SCHEMA, TABLE_NAME) AS TOTAL_TABLES
     , COUNT_IF(PK_COLUMNS = 1) as ONE_PK_COLUMN
     , COUNT_IF(PK_COLUMNS = 2) / 2 as TWO_PK_COLUMNS
     , count(*) AS TOTAL_COLUMNS
FROM MS_RAW.STG_META.T_PRIMARY_KEYS
;

-- 233 MASTER PK
SELECT COLUMN_NAME, TABLE_NAME, NEW_TABLE_NAME, NEW_COLUMN_NAME
  FROM MS_RAW.STG_META.T_PRIMARY_KEYS 
 WHERE PK_COLUMNS = 1 
   AND NEW_COLUMN_NAME = NEW_TABLE_NAME || '_ID' 
ORDER BY ALL;


-- 42 PK ARE SAME AS MASTER PK
SELECT MK.NEW_COLUMN_NAME AS MK_NEW_COLUMN_NAME, PK.*
FROM MS_RAW.STG_META.T_PRIMARY_KEYS PK -- WHERE COLUMN_NAME = 'CANDIDATE_ID'
   , MS_RAW.STG_META.T_PRIMARY_KEYS MK
 WHERE MK.PK_COLUMNS = 1 
   AND MK.NEW_COLUMN_NAME = MK.NEW_TABLE_NAME || '_ID' 
   AND MK.COLUMN_NAME = PK.COLUMN_NAME
   AND MK.TABLE_NAME != PK.TABLE_NAME
ORDER BY ALL;

-- 42 PK ARE SAME AS MASTER PK ---------------------------------------------------
UPDATE MS_RAW.STG_META.T_PRIMARY_KEYS PK
   SET NEW_COLUMN_NAME = MK.NEW_COLUMN_NAME
     , IS_MASTER_ID = TRUE
  FROM MS_RAW.STG_META.T_PRIMARY_KEYS MK
 WHERE MK.PK_COLUMNS = 1 
   AND MK.NEW_COLUMN_NAME = MK.NEW_TABLE_NAME || '_ID' 
   AND MK.COLUMN_NAME = PK.COLUMN_NAME
   AND MK.TABLE_NAME != PK.TABLE_NAME
;

-- 299 ------------------------------------------------------------------------
UPDATE MS_RAW.STG_META.SF_TABLES AS t
   SET PRIMARY_KEY_NAME     = CASE WHEN pk.PK_COLUMNS = 2
                                   THEN pk.NEW_TABLE_NAME_ID
                                   ELSE pk.COLUMN_NAME
                              END,
       PK_COLUMNS           = pk.PK_COLUMNS,
       PK_TABLES            = pk.PK_TABLES,
       NEW_PRIMARY_KEY_NAME = NEW_COLUMN_NAME,
       NEW_PRIMARY_KEY_EXPRESSION =
            CASE WHEN pk.PK_COLUMNS = 2
                 THEN '(' || pk.KEY_PART_2 || ' * POWER(10, 12) + ' || pk.KEY_PART_1 || ')::NUMERIC(24,0)'
                 ELSE NULL
            END,
       NEW_PRIMARY_KEY_UNIQUE_COLUMNS =
            CASE WHEN pk.PK_COLUMNS = 2
                 THEN pk.KEY_PART_2 || ',' || pk.KEY_PART_1
                 ELSE NULL
            END
   FROM MS_RAW.STG_META.T_PRIMARY_KEYS AS pk
  WHERE pk.table_schema = t.table_schema
    AND pk.table_name   = t.table_name
    AND pk.ORDINAL_POSITION = 1
;


-- 21 -- CREATE NEW _ID COLUMN FOR TABLES WHERE PK_COLUMNS = 2 ---------------------------------
INSERT INTO MS_RAW.STG_META.SF_COLUMNS
      (TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME,
       NEW_COLUMN_NAME, 
       NEW_COLUMN_EXPRESSION)
SELECT TABLE_SCHEMA, TABLE_NAME, PRIMARY_KEY_NAME,
       NEW_PRIMARY_KEY_NAME AS NEW_COLUMN_NAME, 
       NEW_PRIMARY_KEY_EXPRESSION AS NEW_COLUMN_EXPRESSION
FROM MS_RAW.STG_META.SF_TABLES AS T
WHERE PK_COLUMNS = 2
  AND NOT EXISTS (SELECT 1 FROM MS_RAW.STG_META.SF_COLUMNS AS S
                  WHERE S.TABLE_SCHEMA = T.TABLE_SCHEMA
                    AND S.TABLE_NAME   = T.TABLE_NAME
                    AND S.NEW_COLUMN_NAME  = T.NEW_PRIMARY_KEY_NAME
                    AND T.NEW_PRIMARY_KEY_NAME ILIKE '%_ID')  
ORDER BY TABLE_SCHEMA, TABLE_NAME, PRIMARY_KEY_NAME, NEW_PRIMARY_KEY_NAME
; 

-- 285 UPDATE ALL PK COLUMNS ---------------------------
UPDATE MS_RAW.STG_META.SF_COLUMNS AS C
   SET NEW_COLUMN_NAME = T.NEW_PRIMARY_KEY_NAME
     , NEW_COLUMN_EXPRESSION = T.NEW_PRIMARY_KEY_EXPRESSION
FROM MS_RAW.STG_META.SF_TABLES AS T
WHERE C.TABLE_SCHEMA = T.TABLE_SCHEMA
  AND C.TABLE_NAME   = T.TABLE_NAME
  AND C.COLUMN_NAME  = T.PRIMARY_KEY_NAME
;

-- 731 _IDs THAT EXIST AS PK
SELECT *
FROM MS_RAW.STG_META.SF_COLUMNS C 
WHERE NEW_COLUMN_NAME ILIKE '%_ID'
  AND EXISTS (SELECT 1 FROM MS_RAW.STG_META.SF_TABLES T WHERE T.NEW_PRIMARY_KEY_NAME = C.NEW_COLUMN_NAME)
ORDER BY NEW_COLUMN_NAME
;

-- 174 _IDs THAT DO NOT EXIST AS PK AND WILL BE CORRECTED WITH THE FK
SELECT NEW_COLUMN_NAME, *
FROM MS_RAW.STG_META.SF_COLUMNS C 
WHERE NEW_COLUMN_NAME ILIKE '%_ID'
  AND NOT EXISTS (SELECT 1 FROM MS_RAW.STG_META.SF_TABLES T WHERE T.NEW_PRIMARY_KEY_NAME = C.NEW_COLUMN_NAME)
ORDER BY ALL
;


SELECT * FROM MS_RAW.STG_META.SF_TABLES WHERE NEW_PRIMARY_KEY_NAME = 'JOB_APPLICATION_ID'; -- CURRENTLY IS 'APPLICATION_ID';
SELECT * FROM MS_RAW.STG_META.SF_TABLES WHERE NEW_TABLE_NAME = 'JOB_APPLICATION'; -- CURRENTLY IS 'APPLICATION_ID';
