CREATE OR REPLACE TRANSIENT TABLE MS_RAW.STG_META.T_SECONDARY_KEYS AS
WITH fk_cols AS (
    SELECT
        tc.CONSTRAINT_NAME,
        tc.TABLE_SCHEMA,
        tc.TABLE_NAME,
        kcu.COLUMN_NAME,
        sfc.SF_TABLE_SCHEMA,
        sfc.SF_TABLE_NAME,
        sft.NEW_TABLE_NAME,
        sfc.SF_COLUMN_NAME,
        sfc.NEW_COLUMN_NAME,
        ROW_NUMBER() OVER (
            PARTITION BY tc.CONSTRAINT_NAME
            ORDER BY kcu.ORDINAL_POSITION
        ) AS column_ordinal
    FROM ROL_RAW.REEDONLINE_META.TABLE_CONSTRAINTS tc
    JOIN ROL_RAW.REEDONLINE_META.KEY_COLUMN_USAGE kcu
      ON tc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME
     AND tc.TABLE_SCHEMA     = kcu.TABLE_SCHEMA
    JOIN MS_RAW.STG_META.SF_COLUMNS sfc
      ON tc.TABLE_SCHEMA     = sfc.MS_TABLE_SCHEMA
     AND tc.TABLE_NAME       = sfc.MS_TABLE_NAME
     AND kcu.COLUMN_NAME     = sfc.MS_COLUMN_NAME
    JOIN MS_RAW.STG_META.SF_TABLES sft
      ON tc.TABLE_SCHEMA     = sft.MS_TABLE_SCHEMA
     AND tc.TABLE_NAME       = sft.MS_TABLE_NAME
    WHERE tc.CONSTRAINT_TYPE = 'FOREIGN KEY'
      AND sfc.SF_TABLE_NAME != 'PRICEBOOK_ENTRY'
    ORDER BY ALL
),
pk_cols AS (
    SELECT
        tc.CONSTRAINT_NAME,
        tc.TABLE_SCHEMA,
        tc.TABLE_NAME,
        kcu.COLUMN_NAME,
        sfc.SF_TABLE_SCHEMA,
        sfc.SF_TABLE_NAME,
        sft.NEW_TABLE_NAME,
        sfc.SF_COLUMN_NAME,
        sfc.NEW_COLUMN_NAME,
        ROW_NUMBER() OVER (
            PARTITION BY tc.CONSTRAINT_NAME
            ORDER BY kcu.ORDINAL_POSITION
        ) AS column_ordinal,
        COUNT(*) OVER (
            PARTITION BY tc.CONSTRAINT_NAME
        ) AS total_columns
    FROM ROL_RAW.REEDONLINE_META.TABLE_CONSTRAINTS tc
    JOIN ROL_RAW.REEDONLINE_META.KEY_COLUMN_USAGE kcu
      ON tc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME
     AND tc.TABLE_SCHEMA     = kcu.TABLE_SCHEMA
    JOIN MS_RAW.STG_META.SF_COLUMNS sfc
      ON tc.TABLE_SCHEMA     = sfc.MS_TABLE_SCHEMA
     AND tc.TABLE_NAME       = sfc.MS_TABLE_NAME
     AND kcu.COLUMN_NAME     = sfc.MS_COLUMN_NAME
    JOIN MS_RAW.STG_META.SF_TABLES sft
      ON tc.TABLE_SCHEMA     = sft.MS_TABLE_SCHEMA
     AND tc.TABLE_NAME       = sft.MS_TABLE_NAME
    WHERE tc.CONSTRAINT_TYPE IN ('PRIMARY KEY', 'UNIQUE')
    ORDER BY 2,3,5
)
SELECT
    fk_cols.SF_TABLE_SCHEMA   AS fk_TABLE_SCHEMA,
    fk_cols.SF_TABLE_NAME     AS fk_TABLE_NAME,
    fk_cols.SF_COLUMN_NAME    AS fk_COLUMN_NAME,
    fk_cols.NEW_TABLE_NAME    AS fk_NEW_TABLE_NAME,
    fk_cols.NEW_COLUMN_NAME   AS fk_NEW_COLUMN_NAME,
    fk_cols.CONSTRAINT_NAME   AS fk_constraint_name,
    pk_cols.SF_TABLE_SCHEMA   AS pk_TABLE_SCHEMA,
    pk_cols.SF_TABLE_NAME     AS pk_TABLE_NAME,
    pk_cols.SF_COLUMN_NAME    AS pk_COLUMN_NAME,
    pk_cols.NEW_TABLE_NAME    AS pk_NEW_TABLE_NAME,
    pk_cols.NEW_COLUMN_NAME   AS pk_NEW_COLUMN_NAME,
    pk_cols.CONSTRAINT_NAME   AS pk_constraint_name,
    pk_cols.column_ordinal    AS pk_ordinal_position,
    pk_cols.total_columns     AS pk_total_columns
FROM ROL_RAW.REEDONLINE_META.REFERENTIAL_CONSTRAINTS rc
JOIN fk_cols
  ON rc.CONSTRAINT_NAME = fk_cols.CONSTRAINT_NAME
JOIN pk_cols
  ON rc.UNIQUE_CONSTRAINT_NAME = pk_cols.CONSTRAINT_NAME
 AND fk_cols.column_ordinal    = pk_cols.column_ordinal
ORDER BY
    fk_TABLE_SCHEMA,
    fk_TABLE_NAME,
    fk_constraint_name,
    pk_ordinal_position
;

-- NO MISSING
SELECT * 
FROM MS_RAW.STG_META.T_SECONDARY_KEYS
WHERE FK_NEW_COLUMN_NAME IS NULL
   OR FK_NEW_TABLE_NAME  IS NULL
   OR PK_NEW_COLUMN_NAME IS NULL
   OR PK_NEW_TABLE_NAME  IS NULL
ORDER BY ALL
;


----------------------- read for dbt tests -----------------------------
-- NEW TEST FOR FK -> PK(2 COLUMNS)
CREATE OR REPLACE TRANSIENT TABLE MS_RAW.STG_META.T_TWO_KEYS_DBT_TEST AS
SELECT *
FROM MS_RAW.STG_META.T_SECONDARY_KEYS
WHERE pk_total_columns = 2
;

DELETE FROM MS_RAW.STG_META.T_SECONDARY_KEYS
WHERE fk_constraint_name IN (SELECT fk_constraint_name 
                             FROM MS_RAW.STG_META.T_TWO_KEYS_DBT_TEST)
;


----------------- add new columns to the fk tables

SELECT *
FROM MS_RAW.STG_META.T_TWO_KEYS_DBT_TEST fk2
INNER JOIN MS_RAW.STG_META.SF_TABLES sft2
   ON fk2.PK_TABLE_SCHEMA = sft2.SF_TABLE_SCHEMA
  AND fk2.PK_TABLE_NAME   = sft2.SF_TABLE_NAME
WHERE sft2.PK_COLUMNS = 2
  AND FK_NEW_COLUMN_NAME = PK_NEW_COLUMN_NAME
ORDER BY ALL
;

SELECT FK_TABLE_SCHEMA, FK_TABLE_NAME, NEW_PRIMARY_KEY_NAME
       NEW_PRIMARY_KEY_NAME, 'NUMERIC(18,0)', NEW_PRIMARY_KEY_EXPRESSION
FROM MS_RAW.STG_META.T_TWO_KEYS_DBT_TEST fk2
INNER JOIN MS_RAW.STG_META.SF_TABLES sft2
   ON fk2.PK_TABLE_SCHEMA = sft2.SF_TABLE_SCHEMA
  AND fk2.PK_TABLE_NAME   = sft2.SF_TABLE_NAME
WHERE sft2.PK_COLUMNS = 2
  AND FK_NEW_COLUMN_NAME = PK_NEW_COLUMN_NAME
  AND (FK_TABLE_SCHEMA, FK_TABLE_NAME, NEW_PRIMARY_KEY_NAME)
      NOT IN (SELECT SF_TABLE_SCHEMA, SF_TABLE_NAME, SF_COLUMN_NAME
                FROM MS_RAW.STG_META.SF_COLUMNS)
GROUP BY ALL
ORDER BY ALL
;

INSERT INTO MS_RAW.STG_META.SF_COLUMNS
      (SF_TABLE_SCHEMA, SF_TABLE_NAME, SF_COLUMN_NAME, 
       NEW_COLUMN_NAME, NEW_COLUMN_TYPE, NEW_COLUMN_EXPRESSION)
SELECT FK_TABLE_SCHEMA, FK_TABLE_NAME, NEW_PRIMARY_KEY_NAME,
       NEW_PRIMARY_KEY_NAME, 'NUMERIC(18,0)', NEW_PRIMARY_KEY_EXPRESSION
FROM MS_RAW.STG_META.T_TWO_KEYS_DBT_TEST fk2
INNER JOIN MS_RAW.STG_META.SF_TABLES sft2
   ON fk2.PK_TABLE_SCHEMA = sft2.SF_TABLE_SCHEMA
  AND fk2.PK_TABLE_NAME   = sft2.SF_TABLE_NAME
WHERE sft2.PK_COLUMNS = 2
  AND FK_NEW_COLUMN_NAME = PK_NEW_COLUMN_NAME
  AND (FK_TABLE_SCHEMA, FK_TABLE_NAME, NEW_PRIMARY_KEY_NAME)
      NOT IN (SELECT SF_TABLE_SCHEMA, SF_TABLE_NAME, SF_COLUMN_NAME
                FROM MS_RAW.STG_META.SF_COLUMNS)
GROUP BY ALL
ORDER BY ALL
;

INSERT INTO MS_RAW.STG_META.T_SECONDARY_KEYS
      (fk_TABLE_SCHEMA, fk_TABLE_NAME, fk_COLUMN_NAME, fk_NEW_TABLE_NAME, fk_NEW_COLUMN_NAME, fk_constraint_name,
       pk_TABLE_SCHEMA, pk_TABLE_NAME, pk_COLUMN_NAME, pk_NEW_TABLE_NAME, pk_NEW_COLUMN_NAME, pk_constraint_name,
       pk_ordinal_position, pk_total_columns)
SELECT FK_TABLE_SCHEMA, FK_TABLE_NAME, NEW_PRIMARY_KEY_NAME, fk_NEW_TABLE_NAME, NEW_PRIMARY_KEY_NAME, 'NFK_' || fk_NEW_TABLE_NAME || PK_NEW_TABLE_NAME,
       pk_TABLE_SCHEMA, pk_TABLE_NAME, NEW_PRIMARY_KEY_NAME, pk_NEW_TABLE_NAME, NEW_PRIMARY_KEY_NAME, 'NPK_' || PK_NEW_TABLE_NAME,
       1, 1
FROM MS_RAW.STG_META.T_TWO_KEYS_DBT_TEST fk2
INNER JOIN MS_RAW.STG_META.SF_TABLES sft2
   ON fk2.PK_TABLE_SCHEMA = sft2.SF_TABLE_SCHEMA
  AND fk2.PK_TABLE_NAME   = sft2.SF_TABLE_NAME
WHERE sft2.PK_COLUMNS = 2
  AND FK_NEW_COLUMN_NAME = PK_NEW_COLUMN_NAME
  AND (FK_TABLE_SCHEMA, FK_TABLE_NAME, NEW_PRIMARY_KEY_NAME)
      NOT IN (SELECT SF_TABLE_SCHEMA, SF_TABLE_NAME, SF_COLUMN_NAME
                FROM MS_RAW.STG_META.SF_COLUMNS)
GROUP BY ALL
ORDER BY ALL
;
     
