TO CHECK IF CAN IMPROUVE THE NAMINGS AND IGNORE DUPLICATES


-- 496 FK
CREATE OR REPLACE TRANSIENT TABLE MS_RAW.STG_META.T_FOREIGN_KEYS AS
SELECT
       KCU.CONSTRAINT_NAME  AS FK_MS_CONSTRAINT_NAME
     , ST.MS_TABLE_SCHEMA   AS FK_MS_TABLE_SCHEMA
     , ST.MS_TABLE_NAME     AS FK_MS_TABLE_NAME
     , SC.MS_COLUMN_NAME    AS FK_MS_COLUMN_NAME 
     , KCU.ORDINAL_POSITION AS FK_ORDINAL_POSITION   
     , SC.TABLE_SCHEMA      AS FK_TABLE_SCHEMA
     , SC.TABLE_NAME        AS FK_TABLE_NAME
     , SC.COLUMN_NAME       AS FK_COLUMN_NAME
     , ST.NEW_TABLE_NAME    AS FK_NEW_TABLE_NAME
     , SC.NEW_COLUMN_NAME   AS FK_NEW_COLUMN_NAME
     , PK.*
FROM ROL_RAW.REEDONLINE_META.TABLE_CONSTRAINTS TC
INNER JOIN MS_RAW.STG_META.SF_TABLES ST
    ON TC.TABLE_SCHEMA = ST.MS_TABLE_SCHEMA
   AND TC.TABLE_NAME   = ST.MS_TABLE_NAME
INNER JOIN ROL_RAW.REEDONLINE_META.KEY_COLUMN_USAGE KCU
    ON TC.CONSTRAINT_SCHEMA = KCU.CONSTRAINT_SCHEMA
   AND TC.CONSTRAINT_NAME   = KCU.CONSTRAINT_NAME
INNER JOIN ROL_RAW.REEDONLINE_META.REFERENTIAL_CONSTRAINTS RC
    ON TC.CONSTRAINT_SCHEMA = RC.CONSTRAINT_SCHEMA
   AND TC.CONSTRAINT_NAME   = RC.CONSTRAINT_NAME
INNER JOIN MS_RAW.STG_META.MS_INDEXES IX
    ON RC.UNIQUE_CONSTRAINT_SCHEMA = IX.TABLE_SCHEMA
   AND RC.UNIQUE_CONSTRAINT_NAME   = IX.INDEX_NAME
INNER JOIN MS_RAW.STG_META.T_PRIMARY_KEYS PK
    ON PK.MS_TABLE_SCHEMA    = IX.TABLE_SCHEMA
   AND PK.MS_TABLE_NAME      = IX.TABLE_NAME
   AND PK.ORDINAL_POSITION   = KCU.ORDINAL_POSITION
INNER JOIN MS_RAW.STG_META.SF_COLUMNS SC
    ON KCU.TABLE_SCHEMA = SC.MS_TABLE_SCHEMA
   AND KCU.TABLE_NAME   = SC.MS_TABLE_NAME
   AND KCU.COLUMN_NAME  = SC.MS_COLUMN_NAME
WHERE TC.CONSTRAINT_TYPE = 'FOREIGN KEY'
ORDER BY ALL
;

-- 496
SELECT *
FROM MS_RAW.STG_META.T_FOREIGN_KEYS
ORDER BY ALL
;


??????????????????????????????????????????????????
SELECT TABLE_SCHEMA, TABLE_NAME, FK_TABLE_SCHEMA, FK_TABLE_NAME, 
FROM MS_RAW.STG_META.T_FOREIGN_KEYS
WHERE PK_COLUMNS = 1
GROUP BY ALL
HAVING COUNT(*) > 1
ORDER BY ALL
;

--------------------------------------- NOT USED ---------------------------------------------------
-- 434
SELECT * FROM ROL_RAW.REEDONLINE_META.TABLE_CONSTRAINTS         WHERE TABLE_NAME = 'Candidate_Sector' AND CONSTRAINT_NAME = 'FK_CandidateSector_CandidateID';
SELECT * FROM MS_RAW.STG_META.SF_TABLES ST                      WHERE MS_TABLE_NAME = 'Candidate_Sector';
SELECT * FROM ROL_RAW.REEDONLINE_META.KEY_COLUMN_USAGE          WHERE TABLE_NAME = 'Candidate_Sector' AND CONSTRAINT_NAME = 'FK_CandidateSector_CandidateID';
SELECT * FROM ROL_RAW.REEDONLINE_META.REFERENTIAL_CONSTRAINTS   WHERE CONSTRAINT_NAME = 'FK_CandidateSector_CandidateID';
SELECT * FROM MS_RAW.STG_META.MS_INDEXES                        WHERE INDEX_NAME = 'Uk_Candidate';
SELECT * FROM MS_RAW.STG_META.T_PRIMARY_KEYS                    WHERE PK_CONSTRAINT_NAME = 'PK_Candidate_CandidateID';
ORDER BY ALL
;

SELECT * 
FROM MS_RAW.STG_META.SF_COLUMNS SC
LEFT JOIN MS_RAW.STG_META.T_FOREIGN_KEYS FK
ON  FK_MS_TABLE_SCHEMA = SC.MS_TABLE_SCHEMA
AND FK_MS_TABLE_NAME   = SC.MS_TABLE_NAME
AND FK_MS_COLUMN_NAME  = SC.MS_COLUMN_NAME
LEFT JOIN MS_RAW.STG_META.T_PRIMARY_KEYS PK
ON  PK.TABLE_SCHEMA = SC.TABLE_SCHEMA
AND PK.TABLE_NAME   = SC.TABLE_NAME
AND PK.COLUMN_NAME  = SC.COLUMN_NAME
WHERE SC.MS_TABLE_SCHEMA = 'dbo'
  AND SC.MS_TABLE_NAME = 'Candidate_Sector'
  AND SC.COLUMN_NAME ILIKE '%_ID'
  AND PK.COLUMN_NAME IS NULL
  AND FK_COLUMN_NAME IS NULL
ORDER BY ALL
;


CREATE OR REPLACE TRANSIENT TABLE MS_RAW.STG_META.T_SECONDARY_KEYS AS
WITH fk_cols AS (
    SELECT
        tc.CONSTRAINT_NAME,
        sfc.MS_TABLE_SCHEMA,
        sfc.MS_TABLE_NAME,
        sfc.MS_COLUMN_NAME,
        sfc.TABLE_SCHEMA,
        sfc.TABLE_NAME,
        sft.NEW_TABLE_NAME,
        sfc.COLUMN_NAME,
        sfc.NEW_COLUMN_NAME,
        ROW_NUMBER() OVER (
            PARTITION BY tc.CONSTRAINT_NAME
            ORDER BY kcu.ORDINAL_POSITION
        ) AS column_ordinal
    FROM ROL_RAW.REEDONLINE_META.TABLE_CONSTRAINTS tc
    JOIN ROL_RAW.REEDONLINE_META.KEY_COLUMN_USAGE kcu
      ON tc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME
     AND tc.TABLE_SCHEMA     = kcu.TABLE_SCHEMA
    JOIN MS_RAW.STG_META.SF_COLUMNS sfc
      ON tc.TABLE_SCHEMA     = sfc.MS_TABLE_SCHEMA
     AND tc.TABLE_NAME       = sfc.MS_TABLE_NAME
     AND kcu.COLUMN_NAME     = sfc.MS_COLUMN_NAME
    JOIN MS_RAW.STG_META.SF_TABLES sft
      ON tc.TABLE_SCHEMA     = sft.MS_TABLE_SCHEMA
     AND tc.TABLE_NAME       = sft.MS_TABLE_NAME
    WHERE tc.CONSTRAINT_TYPE = 'FOREIGN KEY'
      AND sfc.TABLE_NAME != 'PRICEBOOK_ENTRY'
    ORDER BY ALL
),
pk_cols AS (
    SELECT
        tc.CONSTRAINT_NAME,
        sfc.MS_TABLE_SCHEMA,
        sfc.MS_TABLE_NAME,
        sfc.MS_COLUMN_NAME,
        sfc.TABLE_SCHEMA,
        sfc.TABLE_NAME,
        sft.NEW_TABLE_NAME,
        sfc.COLUMN_NAME,
        sfc.NEW_COLUMN_NAME,
        ROW_NUMBER() OVER (
            PARTITION BY tc.CONSTRAINT_NAME
            ORDER BY kcu.ORDINAL_POSITION
        ) AS column_ordinal,
        COUNT(*) OVER (
            PARTITION BY tc.CONSTRAINT_NAME
        ) AS total_columns
    FROM ROL_RAW.REEDONLINE_META.TABLE_CONSTRAINTS tc
    JOIN ROL_RAW.REEDONLINE_META.KEY_COLUMN_USAGE kcu
      ON tc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME
     AND tc.TABLE_SCHEMA     = kcu.TABLE_SCHEMA
    JOIN MS_RAW.STG_META.SF_COLUMNS sfc
      ON tc.TABLE_SCHEMA     = sfc.MS_TABLE_SCHEMA
     AND tc.TABLE_NAME       = sfc.MS_TABLE_NAME
     AND kcu.COLUMN_NAME     = sfc.MS_COLUMN_NAME
    JOIN MS_RAW.STG_META.SF_TABLES sft
      ON tc.TABLE_SCHEMA     = sft.MS_TABLE_SCHEMA
     AND tc.TABLE_NAME       = sft.MS_TABLE_NAME
    WHERE tc.CONSTRAINT_TYPE IN ('PRIMARY KEY', 'UNIQUE')
    ORDER BY 2,3,5
)
SELECT
    fk_cols.TABLE_SCHEMA      AS fk_TABLE_SCHEMA,
    fk_cols.TABLE_NAME        AS fk_TABLE_NAME,
    fk_cols.COLUMN_NAME       AS fk_COLUMN_NAME,
    fk_cols.NEW_TABLE_NAME    AS fk_NEW_TABLE_NAME,
    fk_cols.NEW_COLUMN_NAME   AS fk_NEW_COLUMN_NAME,
    fk_cols.CONSTRAINT_NAME   AS fk_constraint_name,
    pk_cols.TABLE_SCHEMA      AS pk_TABLE_SCHEMA,
    pk_cols.TABLE_NAME        AS pk_TABLE_NAME,
    pk_cols.COLUMN_NAME       AS pk_COLUMN_NAME,
    pk_cols.NEW_TABLE_NAME    AS pk_NEW_TABLE_NAME,
    pk_cols.NEW_COLUMN_NAME   AS pk_NEW_COLUMN_NAME,
    pk_cols.CONSTRAINT_NAME   AS pk_constraint_name,
    pk_cols.column_ordinal    AS pk_ordinal_position,
    pk_cols.total_columns     AS pk_total_columns
FROM ROL_RAW.REEDONLINE_META.REFERENTIAL_CONSTRAINTS rc
INNER JOIN MS_RAW.STG_META.MS_INDEXES idx
    ON rc.UNIQUE_CONSTRAINT_NAME = idx.INDEX_NAME
INNER JOIN fk_cols
  ON rc.CONSTRAINT_NAME = fk_cols.CONSTRAINT_NAME
INNER JOIN pk_cols
  ON idx.PK_NAME               = pk_cols.CONSTRAINT_NAME
 AND fk_cols.column_ordinal    = pk_cols.column_ordinal
ORDER BY
    fk_TABLE_SCHEMA,
    fk_TABLE_NAME,
    fk_constraint_name,
    pk_ordinal_position
;
SELECT COUNT(DISTINCT CONSTRAINT_NAME);
SELECT * FROM ROL_RAW.REEDONLINE_META.TABLE_CONSTRAINTS  WHERE CONSTRAINT_TYPE = 'FOREIGN KEY' AND CONSTRAINT_NAME='FK_JobSearchAlert_JobSearchAlertChannelToFrequencyLookup'; -- Reed Online	dbo	Audit
-- CONSTRAINT_CATALOG,CONSTRAINT_SCHEMA,CONSTRAINT_NAME,TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME,CONSTRAINT_TYPE,IS_DEFERRABLE,INITIALLY_DEFERRED,_DLT_LOAD_ID
-- Reed Online,       dbo,              FK_Audit_Users, Reed Online,  dbo,         Audit,     FOREIGN KEY,    NO,NO,1768759285.833804
SELECT * FROM ROL_RAW.REEDONLINE_META.KEY_COLUMN_USAGE WHERE CONSTRAINT_SCHEMA = 'dbo' AND CONSTRAINT_NAME='FK_JobSearchAlert_JobSearchAlertChannelToFrequencyLookup';
-- CONSTRAINT_CATALOG,CONSTRAINT_SCHEMA,CONSTRAINT_NAME,TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME,ORDINAL_POSITION,_DLT_LOAD_ID
-- Reed Online,       dbo,              FK_Audit_Users, Reed Online,  dbo,         Audit,     UserId,1,1768759285.833804
SELECT * FROM ROL_RAW.REEDONLINE_META.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_JobSearchAlert_JobSearchAlertChannelToFrequencyLookup'; 
-- CONSTRAINT_CATALOG,CONSTRAINT_SCHEMA,CONSTRAINT_NAME,UNIQUE_CONSTRAINT_CATALOG,UNIQUE_CONSTRAINT_SCHEMA,UNIQUE_CONSTRAINT_NAME,MATCH_OPTION,UPDATE_RULE,DELETE_RULE,_DLT_LOAD_ID
-- Reed Online,       dbo,              FK_Audit_Users, Reed Online,              dbo,                     Users_UserID,          SIMPLE,NO ACTION,NO ACTION,1768759285.833804
SELECT * FROM ROL_RAW.REEDONLINE_META.TABLE_CONSTRAINTS  WHERE CONSTRAINT_NAME='PK_JobSearchAlertChannelToFrequencyLookup';
-- CONSTRAINT_CATALOG,CONSTRAINT_SCHEMA,CONSTRAINT_NAME,TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME,CONSTRAINT_TYPE,IS_DEFERRABLE,INITIALLY_DEFERRED,_DLT_LOAD_ID
-- Reed Online,       dbo,              Users_UserID,   Reed Online,  dbo,         Users,     PRIMARY KEY,NO,NO,1768759285.833804
SELECT * FROM MS_RAW.STG_META.T_PRIMARY_KEYS  WHERE CONSTRAINT_NAME='PK_JobSearchAlertChannelToFrequencyLookup';
-- TABLE_SCHEMA,  TABLE_NAME,COLUMN_NAME,MS_TABLE_SCHEMA,MS_TABLE_NAME,MS_COLUMN_NAME,NEW_TABLE_NAME,NEW_TABLE_NAME_ID,NEW_COLUMN_NAME,
--   CONSTRAINT_SCHEMA,CONSTRAINT_NAME,CONSTRAINT_TABLE_NAME,KEY_PART_1,KEY_PART_2,PK_COLUMN_NAMES,PK_COLUMNS,PK_TABLES,ORDINAL_POSITION,IS_MASTER_ID
-- REEDONLINE_DBO,USERS,     USER_ID,    dbo,            Users,        UserId,        USER,          USER_ID,          USER_ID,
--   dbo,             Users_UserID,    Users,                USER_ID,   USER_ID,   USER_ID,        1,         2,        1,               false

SELECT 
       SC.TABLE_SCHEMA      AS FK_TABLE_SCHEMA
     , SC.TABLE_NAME        AS FK_TABLE_NAME
     , KCU.ORDINAL_POSITION AS FK_ORDINAL_POSITION   
     , SC.COLUMN_NAME       AS FK_COLUMN_NAME
     , KCU.CONSTRAINT_NAME  AS FK_CONSTRAINT_NAME
     , PK.*
FROM ROL_RAW.REEDONLINE_META.TABLE_CONSTRAINTS TC
INNER JOIN MS_RAW.STG_META.SF_TABLES ST
    ON TC.TABLE_SCHEMA = ST.MS_TABLE_SCHEMA
   AND TC.TABLE_NAME   = ST.MS_TABLE_NAME
INNER JOIN ROL_RAW.REEDONLINE_META.KEY_COLUMN_USAGE KCU
    ON TC.CONSTRAINT_SCHEMA = KCU.CONSTRAINT_SCHEMA
   AND TC.CONSTRAINT_NAME   = KCU.CONSTRAINT_NAME
INNER JOIN ROL_RAW.REEDONLINE_META.REFERENTIAL_CONSTRAINTS RC
    ON TC.CONSTRAINT_SCHEMA = RC.CONSTRAINT_SCHEMA
   AND TC.CONSTRAINT_NAME   = RC.CONSTRAINT_NAME
INNER JOIN MS_RAW.STG_META.T_PRIMARY_KEYS PK
    ON PK.MS_TABLE_SCHEMA    = RC.UNIQUE_CONSTRAINT_SCHEMA
   AND PK.PK_CONSTRAINT_NAME = RC.UNIQUE_CONSTRAINT_NAME
   AND PK.ORDINAL_POSITION   = KCU.ORDINAL_POSITION
INNER JOIN MS_RAW.STG_META.SF_COLUMNS SC
    ON KCU.TABLE_SCHEMA = SC.MS_TABLE_SCHEMA
   AND KCU.TABLE_NAME   = SC.MS_TABLE_NAME
   AND KCU.COLUMN_NAME  = SC.MS_COLUMN_NAME
WHERE TC.CONSTRAINT_TYPE = 'FOREIGN KEY'
ORDER BY ALL
;
SELECT * FROM MS_RAW.STG_META.SF_COLUMNS WHERE TABLE_NAME = 'Audit';-- AND MS_COLUMN_NAME = 'UserId';

SELECT * FROM MS_RAW.STG_META.SF_TABLES 
WHERE TABLE_NAME ILIKE 'CANDIDATE_AVAILABILITY';
-- 117
SELECT PK_NEW_COLUMN_NAME, FK_NEW_COLUMN_NAME, * EXCLUDE (PK_NEW_COLUMN_NAME, FK_NEW_COLUMN_NAME)
FROM MS_RAW.STG_META.T_SECONDARY_KEYS
WHERE FK_NEW_COLUMN_NAME != PK_NEW_COLUMN_NAME
ORDER BY PK_NEW_COLUMN_NAME, FK_NEW_COLUMN_NAME
;

-- NO MISSING
SELECT * 
FROM MS_RAW.STG_META.T_SECONDARY_KEYS
WHERE FK_NEW_COLUMN_NAME IS NULL
   OR FK_NEW_TABLE_NAME  IS NULL
   OR PK_NEW_COLUMN_NAME IS NULL
   OR PK_NEW_TABLE_NAME  IS NULL
ORDER BY ALL
;


----------------------- read for dbt tests -----------------------------
-- NEW TEST FOR FK -> PK(2 COLUMNS)
CREATE OR REPLACE TRANSIENT TABLE MS_RAW.STG_META.T_TWO_KEYS_DBT_TEST AS
SELECT *
FROM MS_RAW.STG_META.T_SECONDARY_KEYS
WHERE pk_total_columns = 2
;

-- 18
DELETE FROM MS_RAW.STG_META.T_SECONDARY_KEYS
WHERE fk_constraint_name IN (SELECT fk_constraint_name 
                             FROM MS_RAW.STG_META.T_TWO_KEYS_DBT_TEST)
;


----------------- add new columns to the fk tables

-- 17
SELECT *
FROM MS_RAW.STG_META.T_TWO_KEYS_DBT_TEST fk2
INNER JOIN MS_RAW.STG_META.SF_TABLES sft2
   ON fk2.PK_TABLE_SCHEMA = sft2.SF_TABLE_SCHEMA
  AND fk2.PK_TABLE_NAME   = sft2.SF_TABLE_NAME
WHERE sft2.PK_COLUMNS = 2
  AND FK_NEW_COLUMN_NAME = PK_NEW_COLUMN_NAME
ORDER BY ALL
;

-- 9
SELECT FK_TABLE_SCHEMA, FK_TABLE_NAME, NEW_PRIMARY_KEY_NAME
       NEW_PRIMARY_KEY_NAME, 'NUMERIC(18,0)', NEW_PRIMARY_KEY_EXPRESSION
FROM MS_RAW.STG_META.T_TWO_KEYS_DBT_TEST fk2
INNER JOIN MS_RAW.STG_META.SF_TABLES sft2
   ON fk2.PK_TABLE_SCHEMA = sft2.SF_TABLE_SCHEMA
  AND fk2.PK_TABLE_NAME   = sft2.SF_TABLE_NAME
WHERE sft2.PK_COLUMNS = 2
  AND FK_NEW_COLUMN_NAME = PK_NEW_COLUMN_NAME
  AND (FK_TABLE_SCHEMA, FK_TABLE_NAME, NEW_PRIMARY_KEY_NAME)
      NOT IN (SELECT SF_TABLE_SCHEMA, SF_TABLE_NAME, SF_COLUMN_NAME
                FROM MS_RAW.STG_META.SF_COLUMNS)
GROUP BY ALL
ORDER BY ALL
;

-- 9
INSERT INTO MS_RAW.STG_META.SF_COLUMNS
      (SF_TABLE_SCHEMA, SF_TABLE_NAME, SF_COLUMN_NAME, 
       NEW_COLUMN_NAME, NEW_COLUMN_TYPE, NEW_COLUMN_EXPRESSION)
SELECT FK_TABLE_SCHEMA, FK_TABLE_NAME, NEW_PRIMARY_KEY_NAME,
       NEW_PRIMARY_KEY_NAME, 'NUMERIC(18,0)', NEW_PRIMARY_KEY_EXPRESSION
FROM MS_RAW.STG_META.T_TWO_KEYS_DBT_TEST fk2
INNER JOIN MS_RAW.STG_META.SF_TABLES sft2
   ON fk2.PK_TABLE_SCHEMA = sft2.SF_TABLE_SCHEMA
  AND fk2.PK_TABLE_NAME   = sft2.SF_TABLE_NAME
WHERE sft2.PK_COLUMNS = 2
  AND FK_NEW_COLUMN_NAME = PK_NEW_COLUMN_NAME
  AND (FK_TABLE_SCHEMA, FK_TABLE_NAME, NEW_PRIMARY_KEY_NAME)
      NOT IN (SELECT SF_TABLE_SCHEMA, SF_TABLE_NAME, SF_COLUMN_NAME
                FROM MS_RAW.STG_META.SF_COLUMNS)
GROUP BY ALL
ORDER BY ALL
;

-- 0
INSERT INTO MS_RAW.STG_META.T_SECONDARY_KEYS
      (fk_TABLE_SCHEMA, fk_TABLE_NAME, fk_COLUMN_NAME, fk_NEW_TABLE_NAME, fk_NEW_COLUMN_NAME, fk_constraint_name,
       pk_TABLE_SCHEMA, pk_TABLE_NAME, pk_COLUMN_NAME, pk_NEW_TABLE_NAME, pk_NEW_COLUMN_NAME, pk_constraint_name,
       pk_ordinal_position, pk_total_columns)
SELECT FK_TABLE_SCHEMA, FK_TABLE_NAME, NEW_PRIMARY_KEY_NAME, fk_NEW_TABLE_NAME, NEW_PRIMARY_KEY_NAME, 'NFK_' || fk_NEW_TABLE_NAME || PK_NEW_TABLE_NAME,
       pk_TABLE_SCHEMA, pk_TABLE_NAME, NEW_PRIMARY_KEY_NAME, pk_NEW_TABLE_NAME, NEW_PRIMARY_KEY_NAME, 'NPK_' || PK_NEW_TABLE_NAME,
       1, 1
FROM MS_RAW.STG_META.T_TWO_KEYS_DBT_TEST fk2
INNER JOIN MS_RAW.STG_META.SF_TABLES sft2
   ON fk2.PK_TABLE_SCHEMA = sft2.SF_TABLE_SCHEMA
  AND fk2.PK_TABLE_NAME   = sft2.SF_TABLE_NAME
WHERE sft2.PK_COLUMNS = 2
  AND FK_NEW_COLUMN_NAME = PK_NEW_COLUMN_NAME
  AND (FK_TABLE_SCHEMA, FK_TABLE_NAME, NEW_PRIMARY_KEY_NAME)
      NOT IN (SELECT SF_TABLE_SCHEMA, SF_TABLE_NAME, SF_COLUMN_NAME
                FROM MS_RAW.STG_META.SF_COLUMNS)
GROUP BY ALL
ORDER BY ALL
;
     
