-- TO CHECK IF CAN IMPROUVE THE NAMINGS AND IGNORE DUPLICATES

-- 496 FK
CREATE OR REPLACE TRANSIENT TABLE MS_RAW.STG_META.T_FOREIGN_KEYS AS
SELECT
       KCU.CONSTRAINT_NAME  AS FK_MS_CONSTRAINT_NAME
     , ST.MS_TABLE_SCHEMA   AS FK_MS_TABLE_SCHEMA
     , ST.MS_TABLE_NAME     AS FK_MS_TABLE_NAME
     , SC.MS_COLUMN_NAME    AS FK_MS_COLUMN_NAME 
     , KCU.ORDINAL_POSITION AS FK_ORDINAL_POSITION
     , SC.TABLE_SCHEMA      AS FK_TABLE_SCHEMA
     , SC.TABLE_NAME        AS FK_TABLE_NAME
     , SC.COLUMN_NAME       AS FK_COLUMN_NAME
     , ST.NEW_TABLE_NAME    AS FK_NEW_TABLE_NAME
     , SC.NEW_COLUMN_NAME   AS FK_NEW_COLUMN_NAME

     , FIRST_VALUE(FK_COLUMN_NAME)  
        OVER (PARTITION BY FK_MS_TABLE_SCHEMA, FK_MS_CONSTRAINT_NAME ORDER BY FK_ORDINAL_POSITION) 
                            AS FK_KEY_PART_1
     , LAST_VALUE(FK_COLUMN_NAME)  
        OVER (PARTITION BY FK_MS_TABLE_SCHEMA, FK_MS_CONSTRAINT_NAME ORDER BY FK_ORDINAL_POSITION) 
                            AS FK_KEY_PART_2
     , COUNT(*) 
           OVER (PARTITION BY FK_MS_TABLE_SCHEMA, FK_MS_CONSTRAINT_NAME) 
                            AS FK_COLUMNS
     , FALSE                AS IS_FK_SURROGATE_KEY

     , PK.*
     , PT.NEW_PRIMARY_KEY_NAME
     , PT.NEW_PRIMARY_KEY_EXPRESSION
     , PT.NEW_PRIMARY_KEY_UNIQUE_COLUMNS
FROM ROL_RAW.REEDONLINE_META.TABLE_CONSTRAINTS TC
INNER JOIN MS_RAW.STG_META.SF_TABLES ST
    ON TC.TABLE_SCHEMA = ST.MS_TABLE_SCHEMA
   AND TC.TABLE_NAME   = ST.MS_TABLE_NAME
INNER JOIN ROL_RAW.REEDONLINE_META.KEY_COLUMN_USAGE KCU
    ON TC.CONSTRAINT_SCHEMA = KCU.CONSTRAINT_SCHEMA
   AND TC.CONSTRAINT_NAME   = KCU.CONSTRAINT_NAME
INNER JOIN ROL_RAW.REEDONLINE_META.REFERENTIAL_CONSTRAINTS RC
    ON TC.CONSTRAINT_SCHEMA = RC.CONSTRAINT_SCHEMA
   AND TC.CONSTRAINT_NAME   = RC.CONSTRAINT_NAME
INNER JOIN MS_RAW.STG_META.MS_INDEXES IX
    ON RC.UNIQUE_CONSTRAINT_SCHEMA = IX.TABLE_SCHEMA
   AND RC.UNIQUE_CONSTRAINT_NAME   = IX.INDEX_NAME
INNER JOIN MS_RAW.STG_META.T_PRIMARY_KEYS PK
    ON PK.MS_TABLE_SCHEMA    = IX.TABLE_SCHEMA
   AND PK.MS_TABLE_NAME      = IX.TABLE_NAME
   AND PK.ORDINAL_POSITION   = KCU.ORDINAL_POSITION
INNER JOIN MS_RAW.STG_META.SF_COLUMNS SC
    ON KCU.TABLE_SCHEMA = SC.MS_TABLE_SCHEMA
   AND KCU.TABLE_NAME   = SC.MS_TABLE_NAME
   AND KCU.COLUMN_NAME  = SC.MS_COLUMN_NAME
INNER JOIN MS_RAW.STG_META.SF_TABLES PT
    ON PK.MS_TABLE_SCHEMA = PT.MS_TABLE_SCHEMA
   AND PK.MS_TABLE_NAME   = PT.MS_TABLE_NAME
WHERE TC.CONSTRAINT_TYPE = 'FOREIGN KEY'
ORDER BY ALL
;

-- 496
SELECT *
FROM MS_RAW.STG_META.T_FOREIGN_KEYS
ORDER BY ALL
;

-- 0 DUPLICATES
SELECT FK_TABLE_NAME, FK_COLUMN_NAME, NEW_TABLE_NAME
FROM MS_RAW.STG_META.T_FOREIGN_KEYS
GROUP BY ALL 
HAVING COUNT(*) > 1
ORDER BY ALL
;

--- FK WITH 2 COLUMN -> CREATE A NEW COLUMN IN THE SF_COLUMNS & UPDATE FK ------------------------------
-- 18 
SELECT *
FROM MS_RAW.STG_META.T_FOREIGN_KEYS
WHERE FK_COLUMNS > 1
ORDER BY ALL
;
-- 18
SELECT
       FK_KEY_PART_2 || ',' || FK_KEY_PART_1 = NEW_PRIMARY_KEY_UNIQUE_COLUMNS,
       *
FROM MS_RAW.STG_META.T_FOREIGN_KEYS
WHERE FK_COLUMNS = 2
--  AND FK_KEY_PART_2 || ',' || FK_KEY_PART_1 != NEW_PRIMARY_KEY_UNIQUE_COLUMNS  -- 0
ORDER BY ALL
;

-- 9 RAWS
INSERT INTO MS_RAW.STG_META.T_FOREIGN_KEYS
SELECT * 
     REPLACE(
       FK_MS_CONSTRAINT_NAME || '--NEW'  AS FK_MS_CONSTRAINT_NAME
     , NULL     AS FK_MS_TABLE_SCHEMA
     , NULL     AS FK_MS_TABLE_NAME
     , NULL     AS FK_MS_COLUMN_NAME 
     , 0        AS FK_ORDINAL_POSITION
     , 0        AS FK_COLUMNS
     , NEW_PRIMARY_KEY_NAME AS FK_COLUMN_NAME
     , NEW_PRIMARY_KEY_NAME AS FK_NEW_COLUMN_NAME
     , NEW_PRIMARY_KEY_NAME AS COLUMN_NAME
     , NEW_PRIMARY_KEY_NAME AS NEW_COLUMN_NAME
     , NULL     AS MS_TABLE_SCHEMA
     , NULL     AS MS_TABLE_NAME
     , NULL     AS MS_COLUMN_NAME 
     , 1 AS PK_COLUMNS
     )
FROM MS_RAW.STG_META.T_FOREIGN_KEYS AS F
WHERE FK_COLUMNS = 2 AND FK_ORDINAL_POSITION = 1
  AND NOT EXISTS (SELECT 1 FROM MS_RAW.STG_META.T_FOREIGN_KEYS AS K
                  WHERE K.FK_TABLE_SCHEMA        = F.FK_TABLE_SCHEMA
                    AND K.FK_MS_CONSTRAINT_NAME  = F.FK_MS_CONSTRAINT_NAME || '--NEW' )  
ORDER BY ALL                    
;
-- DELETE FROM MS_RAW.STG_META.T_FOREIGN_KEYS WHERE FK_MS_CONSTRAINT_NAME LIKE  '%--NEW'
-- 27
SELECT *
FROM MS_RAW.STG_META.T_FOREIGN_KEYS
WHERE REPLACE(FK_MS_CONSTRAINT_NAME,'--NEW','') IN (SELECT REPLACE(FK_MS_CONSTRAINT_NAME,'--NEW','')
                                                      FROM MS_RAW.STG_META.T_FOREIGN_KEYS
                                                     WHERE FK_MS_CONSTRAINT_NAME ILIKE '%--NEW')
ORDER BY ALL
;

-- 9 -- CREATE NEW _ID COLUMN FOR TABLES WHERE PK_COLUMNS = 2 

INSERT INTO MS_RAW.STG_META.SF_COLUMNS
      (TABLE_SCHEMA, TABLE_NAME, NEW_TABLE_NAME,
       COLUMN_NAME, NEW_COLUMN_NAME, 
       NEW_COLUMN_EXPRESSION)
SELECT FK_TABLE_SCHEMA, FK_NEW_TABLE_NAME, FK_NEW_TABLE_NAME, 
       NEW_PRIMARY_KEY_NAME, NEW_PRIMARY_KEY_NAME, 
       NEW_PRIMARY_KEY_EXPRESSION
FROM MS_RAW.STG_META.T_FOREIGN_KEYS AS T
WHERE FK_MS_CONSTRAINT_NAME ILIKE '%--NEW'
  AND NOT EXISTS (SELECT 1 FROM MS_RAW.STG_META.SF_COLUMNS AS S
                  WHERE S.TABLE_SCHEMA     = T.FK_TABLE_SCHEMA
                    AND S.TABLE_NAME       = T.FK_NEW_TABLE_NAME
                    AND S.NEW_COLUMN_NAME  = T.NEW_PRIMARY_KEY_NAME)  
ORDER BY ALL
;

-- 27
SELECT *
FROM MS_RAW.STG_META.T_FOREIGN_KEYS F
WHERE  REPLACE(FK_MS_CONSTRAINT_NAME,'--NEW','') IN (SELECT REPLACE(FK_MS_CONSTRAINT_NAME,'--NEW','')
                                                       FROM MS_RAW.STG_META.T_FOREIGN_KEYS
                                                      WHERE FK_MS_CONSTRAINT_NAME LIKE  '%--NEW')
ORDER BY ALL;


-- 18
-- DELETE FROM MS_RAW.STG_META.T_FOREIGN_KEYS
-- WHERE PK_COLUMNS > 1
;

---------- END OF FK WITH 2 COLUMNS ---------------------------------------------------------------------


---------- FK_COLUMNS = 1 AND FK_COLUMN_NAME ILIKE '%_BW' ---------------------------------------------------------------------

-- 7 _BW
SELECT TABLE_SCHEMA, FK_NEW_TABLE_NAME, FK_NEW_COLUMN_NAME, FK_ORDINAL_POSITION, NEW_TABLE_NAME, NEW_COLUMN_NAME 
FROM MS_RAW.STG_META.T_FOREIGN_KEYS F
WHERE FK_COLUMNS = 1 AND FK_COLUMN_NAME ILIKE '%_BW'
-- AND FK_NEW_COLUMN_NAME = REPLACE(FK_COLUMN_NAME,'_BW','_ID') -- 0
-- AND    NEW_COLUMN_NAME = REPLACE(FK_COLUMN_NAME,'_BW','_ID') -- 7
ORDER BY ALL
;
UPDATE MS_RAW.STG_META.T_FOREIGN_KEYS
   SET FK_NEW_COLUMN_NAME = NEW_COLUMN_NAME
 WHERE FK_COLUMNS = 1 AND FK_COLUMN_NAME ILIKE '%_BW'
;
-- 7 _BW
SELECT TABLE_SCHEMA, FK_NEW_TABLE_NAME, FK_NEW_COLUMN_NAME, FK_ORDINAL_POSITION, NEW_TABLE_NAME, NEW_COLUMN_NAME 
FROM MS_RAW.STG_META.T_FOREIGN_KEYS F
WHERE FK_COLUMNS = 1 AND FK_COLUMN_NAME ILIKE '%_BW'
-- AND FK_NEW_COLUMN_NAME = REPLACE(FK_COLUMN_NAME,'_BW','_ID') -- 7
-- AND    NEW_COLUMN_NAME = REPLACE(FK_COLUMN_NAME,'_BW','_ID') -- 7
ORDER BY ALL
;
---------- END    FK_COLUMNS = 1 AND FK_COLUMN_NAME ILIKE '%_BW' ---------------------------------------------------------------------

-------------------- RAZNI -------------------------------------------------------------------------


-- 2 DUPLICATES
SELECT *
FROM MS_RAW.STG_META.T_FOREIGN_KEYS
WHERE (FK_TABLE_NAME, FK_COLUMN_NAME) 
   IN (SELECT FK_TABLE_NAME, FK_COLUMN_NAME
         FROM MS_RAW.STG_META.T_FOREIGN_KEYS
        GROUP BY ALL 
       HAVING COUNT(*) > 1)
ORDER BY ALL
;

-- 505
SELECT TABLE_SCHEMA, FK_NEW_COLUMN_NAME, NEW_COLUMN_NAME, FK_NEW_TABLE_NAME, NEW_TABLE_NAME
--SELECT *
FROM MS_RAW.STG_META.T_FOREIGN_KEYS
WHERE 1 = 1
-- AND FK_NEW_COLUMN_NAME  = NEW_COLUMN_NAME AND NEW_COLUMN_NAME  = NEW_TABLE_NAME || '_ID' -- 351
-- AND FK_NEW_COLUMN_NAME  = NEW_COLUMN_NAME AND NEW_COLUMN_NAME != NEW_TABLE_NAME || '_ID' -- 41 -> THE 2 COLUMN NAMES TO BE REDACTED TO THE PK_TABLE || 'ID'
-- AND FK_NEW_COLUMN_NAME != NEW_COLUMN_NAME -- 113
ORDER BY ALL
;

-- 5
SELECT  TABLE_SCHEMA, FK_NEW_TABLE_NAME, FK_MS_CONSTRAINT_NAME, FK_NEW_COLUMN_NAME, NEW_TABLE_NAME, NEW_COLUMN_NAME 
--SELECT *
FROM MS_RAW.STG_META.T_FOREIGN_KEYS F
WHERE 1 = 1
AND EXISTS (SELECT 1 FROM MS_RAW.STG_META.T_FOREIGN_KEYS W 
                     WHERE W.FK_NEW_COLUMN_NAME ILIKE '%_BW'
                       AND W.FK_NEW_TABLE_NAME = F.FK_NEW_TABLE_NAME)
ORDER BY FK_NEW_TABLE_NAME, FK_NEW_COLUMN_NAME
;


-- 487
SELECT TABLE_SCHEMA, NEW_TABLE_NAME, NEW_COLUMN_NAME, FK_NEW_TABLE_NAME, FK_NEW_COLUMN_NAME
FROM MS_RAW.STG_META.T_FOREIGN_KEYS
WHERE PK_COLUMNS = 1
--  AND NEW_COLUMN_NAME  = FK_NEW_COLUMN_NAME -- 374
  AND NEW_COLUMN_NAME != FK_NEW_COLUMN_NAME -- 113
ORDER BY ALL
;
SELECT TABLE_SCHEMA, NEW_TABLE_NAME, NEW_COLUMN_NAME, FK_NEW_TABLE_NAME, FK_NEW_COLUMN_NAME
FROM MS_RAW.STG_META.T_FOREIGN_KEYS
WHERE PK_COLUMNS = 1
--  AND NEW_COLUMN_NAME  = FK_NEW_COLUMN_NAME -- 374
  AND NEW_COLUMN_NAME != FK_NEW_COLUMN_NAME -- 113
ORDER BY ALL
;

