-- ============================================================================
-- SP_JOIN_METADATA: Join Snowflake and MSSQL metadata
-- ============================================================================
-- Purpose: Create SF_TABLES, SF_COLUMNS, and V_INGESTED_TABLES
-- Parameters:
--   p_exclude_tables: Comma-separated list of tables to exclude (default: 'PRICEBOOKENTRY')
-- Returns: VARCHAR (row counts and success message)
-- ============================================================================

USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE PROCEDURE MS_RAW.DBT_META.SP_JOIN_METADATA(
    p_exclude_tables VARCHAR DEFAULT 'PRICEBOOKENTRY'
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    v_start_time TIMESTAMP_NTZ := CURRENT_TIMESTAMP();
    v_result VARCHAR := '';
    v_step VARCHAR := '';
    v_sf_tables_count NUMBER := 0;
    v_sf_columns_count NUMBER := 0;
BEGIN

    USE DATABASE MS_RAW;
    USE SCHEMA DBT_META;

    -- ========================================================================
    -- STEP 1: Create SF_TABLES (Snowflake + MSSQL table metadata joined)
    -- ========================================================================
    v_step := 'Creating SF_TABLES';

    CREATE OR REPLACE TABLE MS_RAW.DBT_META.SF_TABLES (
        -- Standardized Keys
        SCHEMA_ONLY_KEY VARCHAR(16777216),
        TABLE_ONLY_KEY VARCHAR(16777216),
        TABLE_KEY VARCHAR(16777216) PRIMARY KEY,

        -- Snowflake INFORMATION_SCHEMA metadata
        SF_TABLE_CATALOG VARCHAR(16777216),
        SF_TABLE_SCHEMA VARCHAR(16777216),
        SF_TABLE_NAME VARCHAR(16777216),
        SF_TABLE_TYPE VARCHAR(16777216),
        SF_ROW_COUNT NUMBER,
        SF_BYTES NUMBER,
        SF_CREATED TIMESTAMP_LTZ,
        SF_LAST_ALTERED TIMESTAMP_LTZ,

        -- MSSQL INFORMATION_SCHEMA metadata
        MS_TABLE_CATALOG VARCHAR(16777216),
        MS_TABLE_SCHEMA VARCHAR(16777216),
        MS_TABLE_NAME VARCHAR(16777216),
        MS_TABLE_TYPE VARCHAR(16777216)
    )
    CLUSTER BY (SCHEMA_ONLY_KEY, TABLE_ONLY_KEY)
    COMMENT = 'Joined Snowflake and MSSQL table metadata by TABLE_KEY';

    INSERT INTO MS_RAW.DBT_META.SF_TABLES
    WITH sf_cte AS (
        SELECT
            TABLE_SCHEMA AS SCHEMA_ONLY_KEY,
            UPPER(REPLACE(TABLE_NAME, '_', '')) AS TABLE_ONLY_KEY,
            MS_RAW.DBT_META.UDF_GENERATE_TABLE_KEY(TABLE_SCHEMA, TABLE_NAME) AS TABLE_KEY,
            TABLE_CATALOG,
            TABLE_SCHEMA,
            TABLE_NAME,
            TABLE_TYPE,
            ROW_COUNT,
            BYTES,
            CREATED,
            LAST_ALTERED
        FROM MS_RAW.INFORMATION_SCHEMA.TABLES
        WHERE TABLE_SCHEMA IN ('DBO', 'DUPLICATEJOBSERVICE', 'JOBIMPORT', 'JOBS', 'RECRUITERJOBSTEXTKERNEL')
          AND TABLE_TYPE = 'BASE TABLE'
    ),
    ms_cte AS (
        SELECT
            MS_RAW.DBT_META.UDF_GENERATE_TABLE_KEY(TABLE_SCHEMA, TABLE_NAME) AS TABLE_KEY,
            TABLE_CATALOG,
            TABLE_SCHEMA,
            TABLE_NAME,
            TABLE_TYPE
        FROM MS_RAW.MS_META.TABLES
    )
    SELECT
        sf.SCHEMA_ONLY_KEY,
        sf.TABLE_ONLY_KEY,
        sf.TABLE_KEY,
        sf.TABLE_CATALOG AS SF_TABLE_CATALOG,
        sf.TABLE_SCHEMA AS SF_TABLE_SCHEMA,
        sf.TABLE_NAME AS SF_TABLE_NAME,
        sf.TABLE_TYPE AS SF_TABLE_TYPE,
        sf.ROW_COUNT AS SF_ROW_COUNT,
        sf.BYTES AS SF_BYTES,
        sf.CREATED AS SF_CREATED,
        sf.LAST_ALTERED AS SF_LAST_ALTERED,
        ms.TABLE_CATALOG AS MS_TABLE_CATALOG,
        ms.TABLE_SCHEMA AS MS_TABLE_SCHEMA,
        ms.TABLE_NAME AS MS_TABLE_NAME,
        ms.TABLE_TYPE AS MS_TABLE_TYPE
    FROM sf_cte sf
    LEFT JOIN ms_cte ms ON sf.TABLE_KEY = ms.TABLE_KEY
    ORDER BY sf.TABLE_KEY;

    SELECT COUNT(*) INTO v_sf_tables_count FROM MS_RAW.DBT_META.SF_TABLES;
    v_result := v_result || 'Created SF_TABLES: ' || v_sf_tables_count || ' tables\n';

    -- ========================================================================
    -- STEP 2: Create SF_COLUMNS (Snowflake + MSSQL column metadata joined)
    -- ========================================================================
    v_step := 'Creating SF_COLUMNS';

    CREATE OR REPLACE TABLE MS_RAW.DBT_META.SF_COLUMNS (
        -- Standardized Keys
        SCHEMA_ONLY_KEY VARCHAR(16777216) NOT NULL,
        TABLE_ONLY_KEY VARCHAR(16777216) NOT NULL,
        COLUMN_ONLY_KEY VARCHAR(16777216) NOT NULL,
        TABLE_KEY VARCHAR(16777216) NOT NULL,
        COLUMN_KEY VARCHAR(16777216) PRIMARY KEY,

        -- Snowflake INFORMATION_SCHEMA.COLUMNS metadata (SF_* prefix)
        SF_TABLE_CATALOG VARCHAR(16777216),
        SF_TABLE_SCHEMA VARCHAR(16777216),
        SF_TABLE_NAME VARCHAR(16777216),
        SF_COLUMN_NAME VARCHAR(16777216),
        SF_ORDINAL_POSITION NUMBER(38,0),
        SF_COLUMN_DEFAULT VARCHAR(16777216),
        SF_IS_NULLABLE VARCHAR(3),
        SF_DATA_TYPE VARCHAR(16777216),
        SF_CHARACTER_MAXIMUM_LENGTH NUMBER(38,0),
        SF_CHARACTER_OCTET_LENGTH NUMBER(38,0),
        SF_NUMERIC_PRECISION NUMBER(38,0),
        SF_NUMERIC_PRECISION_RADIX NUMBER(38,0),
        SF_NUMERIC_SCALE NUMBER(38,0),
        SF_DATETIME_PRECISION NUMBER(38,0),
        SF_INTERVAL_TYPE VARCHAR(16777216),
        SF_INTERVAL_PRECISION VARCHAR(16777216),
        SF_CHARACTER_SET_CATALOG VARCHAR(16777216),
        SF_CHARACTER_SET_SCHEMA VARCHAR(16777216),
        SF_CHARACTER_SET_NAME VARCHAR(16777216),
        SF_COLLATION_CATALOG VARCHAR(16777216),
        SF_COLLATION_SCHEMA VARCHAR(16777216),
        SF_COLLATION_NAME VARCHAR(16777216),
        SF_DOMAIN_CATALOG VARCHAR(16777216),
        SF_DOMAIN_SCHEMA VARCHAR(16777216),
        SF_DOMAIN_NAME VARCHAR(16777216),
        SF_UDT_CATALOG VARCHAR(16777216),
        SF_UDT_SCHEMA VARCHAR(16777216),
        SF_UDT_NAME VARCHAR(16777216),
        SF_SCOPE_CATALOG VARCHAR(16777216),
        SF_SCOPE_SCHEMA VARCHAR(16777216),
        SF_SCOPE_NAME VARCHAR(16777216),
        SF_MAXIMUM_CARDINALITY NUMBER(38,0),
        SF_DTD_IDENTIFIER VARCHAR(16777216),
        SF_IS_SELF_REFERENCING VARCHAR(3),
        SF_IS_IDENTITY VARCHAR(3),
        SF_IDENTITY_GENERATION VARCHAR(16777216),
        SF_IDENTITY_START VARCHAR(16777216),
        SF_IDENTITY_INCREMENT VARCHAR(16777216),
        SF_IDENTITY_MAXIMUM VARCHAR(16777216),
        SF_IDENTITY_MINIMUM VARCHAR(16777216),
        SF_IDENTITY_CYCLE VARCHAR(3),
        SF_COMMENT VARCHAR(16777216),

        -- MSSQL INFORMATION_SCHEMA.COLUMNS metadata (MS_* prefix)
        MS_TABLE_CATALOG VARCHAR(16777216),
        MS_TABLE_SCHEMA VARCHAR(16777216),
        MS_TABLE_NAME VARCHAR(16777216),
        MS_COLUMN_NAME VARCHAR(16777216),
        MS_ORDINAL_POSITION NUMBER(19,0),
        MS_COLUMN_DEFAULT VARCHAR(16777216),
        MS_IS_NULLABLE VARCHAR(16777216),
        MS_DATA_TYPE VARCHAR(16777216),
        MS_CHARACTER_MAXIMUM_LENGTH NUMBER(19,0),
        MS_CHARACTER_OCTET_LENGTH NUMBER(19,0),
        MS_NUMERIC_PRECISION NUMBER(19,0),
        MS_NUMERIC_PRECISION_RADIX NUMBER(10,0),
        MS_NUMERIC_SCALE NUMBER(19,0),
        MS_DATETIME_PRECISION NUMBER(10,0),
        MS_CHARACTER_SET_CATALOG VARCHAR(16777216),
        MS_CHARACTER_SET_SCHEMA VARCHAR(16777216),
        MS_CHARACTER_SET_NAME VARCHAR(16777216),
        MS_COLLATION_CATALOG VARCHAR(16777216),
        MS_COLLATION_SCHEMA VARCHAR(16777216),
        MS_COLLATION_NAME VARCHAR(16777216),
        MS_DOMAIN_CATALOG VARCHAR(16777216),
        MS_DOMAIN_SCHEMA VARCHAR(16777216),
        MS_DOMAIN_NAME VARCHAR(16777216)
    )
    CLUSTER BY (TABLE_KEY, SF_ORDINAL_POSITION)
    COMMENT = 'Joined Snowflake and MSSQL column metadata by COLUMN_KEY';

    INSERT INTO MS_RAW.DBT_META.SF_COLUMNS
    WITH sf_cte AS (
        SELECT
            TABLE_SCHEMA AS SCHEMA_ONLY_KEY,
            UPPER(REPLACE(TABLE_NAME, '_', '')) AS TABLE_ONLY_KEY,
            UPPER(REPLACE(COLUMN_NAME, '_', '')) AS COLUMN_ONLY_KEY,
            MS_RAW.DBT_META.UDF_GENERATE_TABLE_KEY(TABLE_SCHEMA, TABLE_NAME) AS TABLE_KEY,
            MS_RAW.DBT_META.UDF_GENERATE_COLUMN_KEY(TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME) AS COLUMN_KEY,
            *
        FROM MS_RAW.INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA IN ('DBO', 'DUPLICATEJOBSERVICE', 'JOBIMPORT', 'JOBS', 'RECRUITERJOBSTEXTKERNEL')
    ),
    ms_cte AS (
        SELECT
            MS_RAW.DBT_META.UDF_GENERATE_COLUMN_KEY(TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME) AS COLUMN_KEY,
            *
        FROM MS_RAW.MS_META.COLUMNS
    )
    SELECT
        sf.SCHEMA_ONLY_KEY,
        sf.TABLE_ONLY_KEY,
        sf.COLUMN_ONLY_KEY,
        sf.TABLE_KEY,
        sf.COLUMN_KEY,
        -- Snowflake metadata (SF_* prefix)
        sf.TABLE_CATALOG AS SF_TABLE_CATALOG,
        sf.TABLE_SCHEMA AS SF_TABLE_SCHEMA,
        sf.TABLE_NAME AS SF_TABLE_NAME,
        sf.COLUMN_NAME AS SF_COLUMN_NAME,
        sf.ORDINAL_POSITION AS SF_ORDINAL_POSITION,
        sf.COLUMN_DEFAULT AS SF_COLUMN_DEFAULT,
        sf.IS_NULLABLE AS SF_IS_NULLABLE,
        sf.DATA_TYPE AS SF_DATA_TYPE,
        sf.CHARACTER_MAXIMUM_LENGTH AS SF_CHARACTER_MAXIMUM_LENGTH,
        sf.CHARACTER_OCTET_LENGTH AS SF_CHARACTER_OCTET_LENGTH,
        sf.NUMERIC_PRECISION AS SF_NUMERIC_PRECISION,
        sf.NUMERIC_PRECISION_RADIX AS SF_NUMERIC_PRECISION_RADIX,
        sf.NUMERIC_SCALE AS SF_NUMERIC_SCALE,
        sf.DATETIME_PRECISION AS SF_DATETIME_PRECISION,
        sf.INTERVAL_TYPE AS SF_INTERVAL_TYPE,
        sf.INTERVAL_PRECISION AS SF_INTERVAL_PRECISION,
        sf.CHARACTER_SET_CATALOG AS SF_CHARACTER_SET_CATALOG,
        sf.CHARACTER_SET_SCHEMA AS SF_CHARACTER_SET_SCHEMA,
        sf.CHARACTER_SET_NAME AS SF_CHARACTER_SET_NAME,
        sf.COLLATION_CATALOG AS SF_COLLATION_CATALOG,
        sf.COLLATION_SCHEMA AS SF_COLLATION_SCHEMA,
        sf.COLLATION_NAME AS SF_COLLATION_NAME,
        sf.DOMAIN_CATALOG AS SF_DOMAIN_CATALOG,
        sf.DOMAIN_SCHEMA AS SF_DOMAIN_SCHEMA,
        sf.DOMAIN_NAME AS SF_DOMAIN_NAME,
        sf.UDT_CATALOG AS SF_UDT_CATALOG,
        sf.UDT_SCHEMA AS SF_UDT_SCHEMA,
        sf.UDT_NAME AS SF_UDT_NAME,
        sf.SCOPE_CATALOG AS SF_SCOPE_CATALOG,
        sf.SCOPE_SCHEMA AS SF_SCOPE_SCHEMA,
        sf.SCOPE_NAME AS SF_SCOPE_NAME,
        sf.MAXIMUM_CARDINALITY AS SF_MAXIMUM_CARDINALITY,
        sf.DTD_IDENTIFIER AS SF_DTD_IDENTIFIER,
        sf.IS_SELF_REFERENCING AS SF_IS_SELF_REFERENCING,
        sf.IS_IDENTITY AS SF_IS_IDENTITY,
        sf.IDENTITY_GENERATION AS SF_IDENTITY_GENERATION,
        sf.IDENTITY_START AS SF_IDENTITY_START,
        sf.IDENTITY_INCREMENT AS SF_IDENTITY_INCREMENT,
        sf.IDENTITY_MAXIMUM AS SF_IDENTITY_MAXIMUM,
        sf.IDENTITY_MINIMUM AS SF_IDENTITY_MINIMUM,
        sf.IDENTITY_CYCLE AS SF_IDENTITY_CYCLE,
        sf.COMMENT AS SF_COMMENT,
        -- MSSQL metadata (MS_* prefix)
        ms.TABLE_CATALOG AS MS_TABLE_CATALOG,
        ms.TABLE_SCHEMA AS MS_TABLE_SCHEMA,
        ms.TABLE_NAME AS MS_TABLE_NAME,
        ms.COLUMN_NAME AS MS_COLUMN_NAME,
        ms.ORDINAL_POSITION AS MS_ORDINAL_POSITION,
        ms.COLUMN_DEFAULT AS MS_COLUMN_DEFAULT,
        ms.IS_NULLABLE AS MS_IS_NULLABLE,
        ms.DATA_TYPE AS MS_DATA_TYPE,
        ms.CHARACTER_MAXIMUM_LENGTH AS MS_CHARACTER_MAXIMUM_LENGTH,
        ms.CHARACTER_OCTET_LENGTH AS MS_CHARACTER_OCTET_LENGTH,
        ms.NUMERIC_PRECISION AS MS_NUMERIC_PRECISION,
        ms.NUMERIC_PRECISION_RADIX AS MS_NUMERIC_PRECISION_RADIX,
        ms.NUMERIC_SCALE AS MS_NUMERIC_SCALE,
        ms.DATETIME_PRECISION AS MS_DATETIME_PRECISION,
        ms.CHARACTER_SET_CATALOG AS MS_CHARACTER_SET_CATALOG,
        ms.CHARACTER_SET_SCHEMA AS MS_CHARACTER_SET_SCHEMA,
        ms.CHARACTER_SET_NAME AS MS_CHARACTER_SET_NAME,
        ms.COLLATION_CATALOG AS MS_COLLATION_CATALOG,
        ms.COLLATION_SCHEMA AS MS_COLLATION_SCHEMA,
        ms.COLLATION_NAME AS MS_COLLATION_NAME,
        ms.DOMAIN_CATALOG AS MS_DOMAIN_CATALOG,
        ms.DOMAIN_SCHEMA AS MS_DOMAIN_SCHEMA,
        ms.DOMAIN_NAME AS MS_DOMAIN_NAME
    FROM sf_cte sf
    LEFT JOIN ms_cte ms ON sf.COLUMN_KEY = ms.COLUMN_KEY
    ORDER BY sf.COLUMN_KEY;

    SELECT COUNT(*) INTO v_sf_columns_count FROM MS_RAW.DBT_META.SF_COLUMNS;
    v_result := v_result || 'Created SF_COLUMNS: ' || v_sf_columns_count || ' columns\n';

    -- ========================================================================
    -- STEP 3: Create V_INGESTED_TABLES (Filtered view)
    -- ========================================================================
    v_step := 'Creating V_INGESTED_TABLES view';

    CREATE OR REPLACE VIEW MS_RAW.DBT_META.V_INGESTED_TABLES AS
    SELECT DISTINCT
        SCHEMA_ONLY_KEY,
        TABLE_ONLY_KEY,
        TABLE_KEY,
        MS_TABLE_SCHEMA,
        MS_TABLE_NAME,
        SF_TABLE_SCHEMA,
        SF_TABLE_NAME
    FROM MS_RAW.DBT_META.SF_COLUMNS
    WHERE MS_TABLE_SCHEMA IS NOT NULL
      AND MS_TABLE_NAME IS NOT NULL
   --   AND UPPER(REPLACE(MS_TABLE_NAME, '_', ''))  
   --       NOT IN (SELECT UPPER(REPLACE(TRIM(VALUE), '_', ''))
   --               FROM TABLE(SPLIT_TO_TABLE(:p_exclude_tables, ','))
   --              )
      ;

    v_result := v_result || 'Created V_INGESTED_TABLES view (excluded: ' || p_exclude_tables || ')\n';

    -- ========================================================================
    -- STEP 4: Return Summary
    -- ========================================================================
    v_result := v_result || '\nMetadata integration completed in '
        || DATEDIFF('second', v_start_time, CURRENT_TIMESTAMP()) || ' seconds';

    RETURN v_result;

EXCEPTION
    WHEN OTHER THEN
        RETURN 'ERROR in step: ' || v_step || '\nError: ' || SQLERRM || '\nStack: ' || SQLCODE;
END;
$$;

-- ============================================================================
-- Grant permissions
-- ============================================================================
GRANT USAGE ON PROCEDURE MS_RAW.DBT_META.SP_JOIN_METADATA(VARCHAR) TO ROLE SYSADMIN;

-- ============================================================================
-- Test execution
-- ============================================================================
-- CALL MS_RAW.DBT_META.SP_JOIN_METADATA('PRICEBOOKENTRY');
