-- JOINS the Snowflake & MSSQL SF_TABLES metadate based on the TABLE_KEY

create or replace TABLE MS_RAW.DBT_META.SF_TABLES (
    SCHEMA_ONLY_KEY VARCHAR(16777216),
    TABLE_ONLY_KEY VARCHAR(16777216),
    TABLE_KEY VARCHAR(16777216),
    SF_TABLE_CATALOG VARCHAR(16777216),
    SF_TABLE_SCHEMA VARCHAR(16777216),
    SF_TABLE_NAME VARCHAR(16777216),
    MS_TABLE_CATALOG VARCHAR(4),
    MS_TABLE_SCHEMA VARCHAR(16777216),
    MS_TABLE_NAME VARCHAR(16777216)
);


INSERT INTO MS_RAW.DBT_META.SF_TABLES
WITH 
sf_cte AS (
    SELECT 
        TABLE_SCHEMA                  AS SCHEMA_ONLY_KEY,
        REPLACE(TABLE_NAME,   '_','') AS TABLE_ONLY_KEY,
        SCHEMA_ONLY_KEY || '.' || TABLE_ONLY_KEY  AS TABLE_KEY,
        TABLE_CATALOG, 
        TABLE_SCHEMA, 
        TABLE_NAME
    --    MS.* EXCLUDE (_DLT_LOAD_ID)
    FROM MS_RAW.INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA IN ('DBO'
                          ,'DUPLICATEJOBSERVICE'
                          ,'JOBIMPORT'
                          ,'JOBS'
                          ,'RECRUITERJOBSTEXTKERNEL')
    ORDER BY TABLE_KEY
)
, ms_cte AS (
    SELECT 
        UPPER(REPLACE((TABLE_SCHEMA || '.' || TABLE_NAME),'_',''))
            AS TABLE_KEY,
        TABLE_CATALOG, 
        TABLE_SCHEMA, 
        TABLE_NAME
    FROM MS_RAW.MS_META.TABLES
)
SELECT 
    sf_cte.*,
    ms_cte.* EXCLUDE (TABLE_KEY)
FROM sf_cte
LEFT JOIN ms_cte
  ON sf_cte.TABLE_KEY = ms_cte.TABLE_KEY
;